### PR TITLE
core: fix configd asList helper

### PR DESCRIPTION
**Pull request by fabianfrz**
fixes the issue that if the element does not exist, I will get an array with a single element which is null element, which again breaks for loops

### CODE REVIEW

**Comment by fabianfrz** [comment]
@fichtner this one is important to merge because @mimugmail found a bug in the nginx plugin caused by this misbehaviour. This bug may break other config templates too (maybe not found yet)

**Comment by AdSchellevis** [comment]
@fabianfrz thanks!

**Comment by mimugmail** [comment]
Does this touch ModelRelationFields? I have some reports that Wireguard Peers doesnt work after 18.7.2 but Wireguard itself stays same version. No idea where to look else

**Comment by fabianfrz** [comment]
no, this should only affect `ArrayField` where this helper is used.
You will now get an empty array instead of one containing an empty value usually known as `null`. With the change, you cannot run into a NPE so easily because the for loops work as expected.

**Pull request merged**
