### PR TITLE
ArrayField - Don't sort unless a sort by field is provided

### PR DESCRIPTION
**Pull request by NOYB**
Avoids default sorting by the 'uuid' so that the default is unsorted.  i.e. config order

### CODE REVIEW

**Comment by AdSchellevis** [comment]
Which problem are you trying to solve? config order itself isn't safe / guaranteed either.

**Comment by NOYB** [comment]
When adding to a list of whatever, you never know the position in the list where to find it due to sorting by the uuid.  The uuid's do not appear to be chronological.  Especially when combining config from another system.

So the default 'uuid' sorting seems kind of random.  From a human perspective doesn't seem useful.  Leaving it unsorted if no sort field is provided seems a little more deterministic from a chronological perspective.  Seems more useful to me.

 

Why isn't config order safe?  It's the same data, just not sorted.

 

As far as guaranteed.  Well 'uuid' order seem kind of random too anyway.

**Comment by AdSchellevis** [comment]
it's is "random" in some sense, just as the ordering in the file would be, hence it doesn't really seem to make sense to change it. We really discourage using config ordering.

**Comment by NOYB** [comment]
Uuid sort doesn't seem to provide any human usefulness.  While unsorted may not be a huge benefit, or guaranteed to strictly follow the config order. It does seem to at least to some degree.  Which seem to tend toward chronological.  Which is somewhat humanly useful.

Though the upside may not be huge, I'm not seeing any downside.  Net positive.

Would appreciate if the project could accommodate this.

Thanks for your consideration.

**Comment by AdSchellevis** [comment]
I'll take a look, I don't mind not sorting (and save cpu cycles), just want to make sure no one assumes anything by the "natural" order of things.

**Comment by NOYB** [comment]
Thanks for taking a second look at this.
I recall seeing only one core feature that doesn't currently provide a sort by field.  Traffic Shaper in 2 of it's 3 searchBase calls.
Don't know about the plugins.  Other than my own.

**Pull request closed without merging**
