### PR TITLE
util: use severity levels

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi!
I hope I didn't miss anything and now we can take advantage of using severity levels?
starting with GUI authentication logging )
Thanks!

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@kulikov-a thanks, it was on my list somewhere to look into this. There are probably more spots to inspect at some point, but this is a good starting point.

**Comment by fichtner** [comment]
FWIW, I don’t think a „log_error“ function should be able to change priority of the message. Some log_error calls are warnings or otherwise but in the end touching those lines should be more clear than obfuscating them as log_error($msg, info);

**Comment by kulikov-a** [comment]
@AdSchellevis Thanks! 
@fichtner @AdSchellevis 

> I don’t think a „log_error“ function should be able to change priority

Can we discuss options then? Maybe it would be more correct to add an additional function (say `log_msg()`) with the severity arg, then go through all the `log_error` calls and change it where appropriate?

**Comment by AdSchellevis** [comment]
I agree the naming is indeed a bit unfortunate, but I also don't want to add functions for every level (growing legacy base with limited value). @kulikov-a your suggestion to wrap the current functionality in `log_msg()` and keep `log_error()` functionally equal sounds reasonable to me.

**Comment by kulikov-a** [comment]
@AdSchellevis Great! (actually, i even started with this approach, but then I decided that the less code the better) )
will you revert pr commits or should i start from the current point?

**Comment by fichtner** [comment]
Yes, generic log message function is better is all I’m saying.

**Comment by AdSchellevis** [comment]
> @AdSchellevis Great! (actually, i even started with this approach, but then I decided that the less code the better) )
> will you revert pr commits or should i start from the current point?

Just stack the change on top, no need to revert the previous code

**Pull request merged**
