### PR TITLE
Unbound overrides: fix handling of wildcard aliases

### PR DESCRIPTION
**Pull request by devin122**
Wildcard functionality of HostnameField was refactored
See f110c988d4c5722308d0ec7a4ef5b86c0b3f767c

### CODE REVIEW

**Comment by AdSchellevis** [comment]
this change is part of the master branch, so we should be good there.

**Comment by devin122** [comment]
I don't follow. This PR fixes a bug introduced via f110c988d4. In that commit the wildcard functionality was broken up, but the model for aliases was not updated (ie the hostname of aliases still refers to the no-longer existent `WildcardAllowed`)

**Comment by AdSchellevis** [comment]
Sorry, my mistake, it seems I replaced one but forgot the other.
https://github.com/opnsense/core/blob/0e3a02bfd2d3af68fc329fc6a33c9e717270eb78/src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml#L101-L104

**Comment by AdSchellevis** [comment]
@devin122 thanks!

**Pull request merged**
