### PR TITLE
Sidebar/hover - modification

### PR DESCRIPTION
**Pull request by opnsenseuser**
Sidebar/hover - modification

### CODE REVIEW

**Comment by fichtner** [comment]
@opnsenseuser I merged it with a few more whitespace / style cleanups to minimise the differences.  I reckon @fabianfrz helped here due to his copyrights? I haven't followed all the discussion. Just asking for confirmation. :)

Thanks, very nice! 👍

**Comment by fabianfrz** [comment]
@fichtner I did not do functional changes - just a small refactoring to clean it up (redundancy)

**Comment by fichtner** [comment]
So "Team Rebellion" is René's copyright? @opnsenseuser do you want to make that more official? in the form of "Your Name <your@email>" -- it's up to you, but it would be nice for the sake of being clear

**Comment by fabianfrz** [comment]
@fichtner my code has only first and last name...

**Comment by opnsenseuser** [comment]
@fichtner I would not mind if Martin agrees. Can I enter my First Name and Suriname in the .js in the Head of the document or would you have another suggestion?

**Pull request closed without merging**
