### PR TITLE
Unbound: typo

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi!
ref. https://forum.opnsense.org/index.php?topic=32597.0
Type casted a bit early imho: may skip updateBlocklist action if model node exists but empty.
Thanks!

### CODE REVIEW

**Comment by AdSchellevis** [comment]
Hi Alex,

The location of the cast looks off indeed, but reading briefly through the code, I don't expect the `if` will be skipped when the node exists in the model as `getNodeByReference()` returns `null` when not found, both "blocklists" and "whitelists" probably always exist in this case. The current fix is good in my opinion, as it implements the proper "does exist" check, I'm just not sure if this was supposed to fix anything else. 

Best regards,

Ad

**Comment by kulikov-a** [comment]
Hi Ad!
i think you are right but it should be without type juggling `if ($item !== null)` for this?

**Comment by AdSchellevis** [comment]
Hi Alex,

An empty string will indeed also match on `!=`, but in this case I do expect an empty object of the FieldType class being returned, which logically doesn't match on `null`.  In this case I don't think the `!=` and `!==` make an actual difference, but both work as far as I'm concerned. Looking at the code, I expect this is only intended to make sure someone doesn't try to inject "hutsefluts" as type which obviously doesn't exist. 

I do believe your current fix is the right one for the intend of the code, if the current issue is that it doesn't want to add a domain when the list is empty, this is likely the proper fix as well.

Best regards,

Ad

**Comment by kulikov-a** [comment]
@AdSchellevis 
> if the current issue is that it doesn't want to add a domain when the list is empty, this is likely the proper fix as well

yes, thanks! )

**Comment by kulikov-a** [comment]
@AdSchellevis Thanks!

**Pull request merged**
