### PR TITLE
webgui: implement lighttpd mod_extforward module

### PR DESCRIPTION
**Pull request by Greelan**
This is a simple implementation of the mod_extforward module in lighttpd, in response to #4638. It relies on enabling the module by default, and allowing the user to configure a configuration file in an include directory to set the `extforward.forwarder` directive. A more sophisticated implementation would allow the user to enable the module by a checkbox in the webgui (rather than enabling it by default), and also set the trusted IPs in the webgui rather than by a manual configuration file. That is for future work :)

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@Greelan it might also be an option to generalise it a bit more and include a directory like `/usr/local/etc/lighttpd_webui/conf.d/` with a readme how to configure additional settings (like extforward).  lighthttp seems to support` server.modules += ("xxx")` in these files and we can document this on our end like we do for some other advanced features as well. What do you think?

**Comment by fichtner** [comment]
It’s what I had in mind when I offered to help on this (sorry btw). Proposal looks promising and with generalisation that is perfect and easy to extend from a future plugin (original concern).

**Comment by kulikov-a** [comment]
@Greelan @AdSchellevis @fichtner 
sorry. do not quite understand. if these are the only directives requested, why not add it directly via the GUI-config-webgui.inc? Or are there even more features planned for the GUI (eg OCSP stapling) via plugin?
thanks!

**Comment by fichtner** [comment]
We've had good experience with the pluggable file inclusion approach (per include directory) and most of the MVC service templating use it as well. It helps to move components to MVC that currently are static, can help split complexity of single configuration files and  also allows users to inject local changes into these files without adding GUI options that are misinterpreted or flagged as bugs for working within their constraints but not user expectations. ;)

**Comment by kulikov-a** [comment]
Ah. got it. thanks!

**Comment by Greelan** [comment]
@fichtner @AdSchellevis thanks for the feedback. I see the sense in your approach. It looks like this is similar in concept to what lighttpd itself is structured around, as seen in `/usr/local/etc/lighttpd/conf.d/`. Indeed with this approach example configs could be added over time to help users.

I should be able to get around to this by the weekend and will aim for submitting a cleaner commit. 😀

@kulikov-a my preference for just the extforward module request was indeed to have this in `webgui.inc`, just for ease of configuration. At the moment that is beyond my ken, but I was hoping down the track I would have time to review similar examples of config options in the existing codebase that I could adapt to get the checkbox, data entry fields and structure to create the `extforward.forwarder` directive.

**Comment by Greelan** [comment]
Superseded by #4837

**Pull request closed without merging**
