### PR TITLE
Fix gateway creation for GRE/GIF tunnels

### PR DESCRIPTION
**Pull request by DasTestament**
I've noticed that there is no GWv4 created for GIF tunnel with configured IPv4 address, but obviously useless GWv6 is successfully created. Current base code does not have any logic for GWv4 creation at all which made me very devastatingly upset so even sun stopped rising every morning upon my house.

This fix allows gateway creation accordingly to the currently configured address space on given iface.

I hope this piece of nano fix will do good.

### CODE REVIEW

**Comment by fichtner** [comment]
Just a remark: The v6 Gateway for gif(4) is not useless, it is for Hurricane Electric Tunnel setups :) https://docs.opnsense.org/manual/how-tos/ipv6_tunnelbroker.html

FWIW, I think this is a fair addition. Handing over to @AdSchellevis for merge.

**Comment by DasTestament** [comment]
You misunderstood me. I meant that if **GIF/GRE tunnel local address** has IPv4 address then GWv6 is totally useless, not **GIF/GRE remote address** =)

**Comment by fichtner** [comment]
You are right, the current implementation is too simplistic / pragmatic in this regard. 😊

**Comment by AdSchellevis** [comment]
sorry, but this looks overly complicated to me.. how about https://github.com/opnsense/core/commit/8cf31215f55d14c47d5a44f836ef0a1a2ea9333c ?

**Comment by fichtner** [comment]
looks good at first glance , but need to redo tunnel setup to be 100% sure. :)

**Comment by DasTestament** [comment]
Well, if 8cf3121 implements the very same logic as in this PR then it's ok by me :)

**Comment by fichtner** [comment]
@DasTestament please test to make sure we're not missing anything! thanks 👍

**Comment by DasTestament** [comment]
Sure thing. Will do it 2morrow.

**Comment by DasTestament** [comment]
Ran few tests and it seems proposed code works as expected ... but, I'm a bit worried that **legacy_interfaces_details()** depends strictly on output order of **ifconfig** ... unlike my code. In theory, proposed code will fail on output order of **ifconfig** change.

**Comment by AdSchellevis** [comment]
**ifconfig** contains what's actually configured, which is generally better/safer to use.

**Comment by DasTestament** [comment]
okay

**Comment by fichtner** [comment]
@DasTestament this will be in 18.1.7 :)

**Comment by DasTestament** [comment]
Ok, waiting for .7 release =)

**Pull request closed without merging**
