### PR TITLE
webgui: lighttpd include directory for configuration

### PR DESCRIPTION
**Pull request by Greelan**
This PR is to replace #4833 and reflects the feedback as to the preferred approach outlined there. It is intended to address #4638 but in a more generic way that will allow configuration of other lighttpd modules

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@Greelan looks good, if @fichtner is also ok with this we can merge it to master

**Review by fichtner — APPROVED** [review]
Looks good. We should remove $lighty_modules post-merge using the same trick Ad suggested in the other PR.

**Comment by Greelan** [comment]
Agree, as long as mod_accesslog is enabled in the order that it currently is through $lighty_modules. It needs to be enabled before mod_extforward, for example, or otherwise mod_extforward won't affect IP logging in the access log

**Comment by Greelan** [comment]
One possible solution to the issue I raised in the comment on my last commit is to have three conf files in the include directory that have the default modules grouped into buckets (`01-default` for default modules that should be loaded first, `10-default` for those second, `20-default` for those last). This is in place of loading them directly in `webgui.inc`. Then a user has the option of including their own confs in the right order “between” those default confs, so that the correct order is achieved.

**Comment by AdSchellevis** [comment]
@Greelan Thanks! In principle I'm not against moving more or less static sections to standard configuration files, it removes custom plumbing from the legacy code and is indeed easier to inject custom overwrites in between as needed (only for advanced users, handle with care :) ). The access log settings can easily be migrated to a jinja template.

**Comment by Greelan** [comment]
@AdSchellevis I am happy to continue tinkering with this if I can get some guidance as to the preferred structure for the default modules and the jinja template - eg any similar structures that already exist for other packages that you could point me to?

**Comment by AdSchellevis** [comment]
@Greelan I think syslog-ng sort of has a similar approach, we didn't refactor the ui pages, but did move the logic into Jinja templates (https://github.com/opnsense/core/tree/master/src/opnsense/service/templates/OPNsense/Syslog). There already is a spot for the web gui, since we generate the php requirements as well (https://github.com/opnsense/core/tree/master/src/opnsense/service/templates/OPNsense/WebGui). We could either add a submodule (subdirectory in there for the conf.d directory) or just start moving settings into a single file, although the first option is probably easiest to read and understand. 

So if you want to take a shot at it, go ahead, I'll try to review and comment when there's a PR.

**Comment by fichtner** [comment]
I don’t mind a rework, but do we need to pick the central web GUI for this if we can already handle the drop ins now? ;)

**Comment by MattElekHarris** [comment]
Is there a target version for this to be included in? Thanks for all your work!

**Comment by Greelan** [comment]
I can't answer that, but you can install it (ie the drop-in directory configuration) now with `opnsense-patch bdf7409 f0e26fe`

**Comment by MattElekHarris** [comment]
Awesome, thanks!

**Comment by Greelan** [comment]
Actually, you might be better with `opnsense-patch 77d562f 24cca59`. The commits above were my original commits. I'm going to test just now

**Pull request merged**
