### PR TITLE
sidebar optimization

### PR DESCRIPTION
**Pull request by opnsenseuser**
sidebar optimization
@fichtner

### CODE REVIEW

**Comment by opnsenseuser** [comment]
@fichtner i do not know why i can´t remove the blanks. i really don´t know :-(

**Comment by opnsenseuser** [comment]
@fichtner i tried 10 times. can´t get the blanks or tabs out of this.

**Comment by fichtner** [comment]
I can merge manually when I’m back home. No worries. :)

**Comment by fichtner** [comment]
merged, thanks!

**Pull request merged**
