### PR TITLE
avoid unnecessary long startup time

### PR DESCRIPTION
**Pull request by fraenki**
re-introduce the short autoboot_delay, avoiding a unnecessary long startup time

### CODE REVIEW

**Comment by fichtner** [comment]
This might sound stupid, but I have to ask. ;) Are you ok with licensing this under the BSD 2-Clause license?

A similar patch is needed in the installer and maybe even the tools. I can add them as well so this is not just a "if you click save settings in the GUI it gets better" but an across-the-board change for all images and installations. @jschellevis are you ok with this?

**Comment by jschellevis** [comment]
Lets go ahead with this.

**Comment by fraenki** [comment]
@fichtner Yes, it's OK to use this under the BSD 2-Clause license.

**Comment by fichtner** [comment]
Thanks, I'll pull this in as soon as 15.1.2 is out. :)

**Comment by fichtner** [comment]
Applied via cherry-pick, thank you. :)

**Pull request closed without merging**
