### PR TITLE
Implement router forwarding for paths containing hyphens

### PR DESCRIPTION
**Pull request by ureyni**
- Implement router forwarding for paths containing hyphens
- Add getQuery() function to handle GET request parameters

### CODE REVIEW

**Comment by fichtner** [comment]
I believe @AdSchellevis wanted to avoid this. Changing URLs to underscore should fix all of this easily.

**Comment by AdSchellevis** [comment]
yes, we had only one of these by mistake, they don't follow the camelcase rules and worked by accident in earlier versions.

**Comment by ureyni** [comment]
Ok @AdSchellevis . We can update our zenarmor codes. what is your say about getQuery function?

**Comment by AdSchellevis** [comment]
@ureyni I'll take a look, don't expect issues with adding a `getQuery()` method which is roughly the same as before.

**Comment by AdSchellevis** [comment]
@ureyni https://github.com/opnsense/core/commit/9d6d7f70031ab4e9ee3ab0a02700cd394a4053bb should do the trick for the getQuery part

**Pull request closed without merging**
