### PR TITLE
Bootstrap srings for the Brazilian Portuguese Translation.

### PR DESCRIPTION
**Pull request by dotike**
Original translators:
<ll@li.org> (Linux Internalationalization Project)
Vinicius Coque <vcoque@gmail.com>

Signed-off-by: Isaac (.ike) Levy <ike@blackskyresearch.net>

### CODE REVIEW

**Comment by dotike** [comment]
On second thought, I'm not sure if this is a good way to go about bootstrapping BR PT.  It may be worth waiting for a Brazillian to chime in and pick up the translation work?

**Comment by fichtner** [comment]
Not sure, how much is this at? I'm only concerned with the source of this translation which isn't fully clear (I'm seeing BSD perimeter, wondering about the history).

**Comment by dotike** [comment]
This file is about 70% of the BR_PT translation.   A sizable chunk, to be sure.

Yet, because I'm unclear about it's the context the strings were originally written, and I'm not in a position to find out, I think it's best to just pull it.

I'll see if I can track down Vinícius Coque and see if he wishes to contribute the translation strings, but for now, I say pull it- I was being rash.

**Comment by fichtner** [comment]
"pull it" as in "in" or "out"?

**Comment by dotike** [comment]
Sorry, I mean pull it out.  (I'll try to connect with Vinícius Coque in Sao Paolo to see if he wants to commit the changes.)

**Comment by fichtner** [comment]
Ok, thanks. :)

**Pull request closed without merging**
