### PR TITLE
Vip alias/dhcp6 fix

### PR DESCRIPTION
**Pull request by marjohn56**
Possible fix for issue #3310  - IP Alias & Tracking LAN.

Remove the VIP alias from the interface before dhcp6c applies a new address and restore the VIP alias after.

### CODE REVIEW

**Comment by marjohn56** [comment]
@fichtner when you've decided what to do with this and don't want or need it, I'll reset my repo as it looks like its a bit naff, not sure how that Replace windows DUID dashes got onto this commit branch.

**Comment by AdSchellevis** [comment]
I think we should be careful with this, often these kind of constructions tend to have boomerang effects later on (an event removes things it's not really responsible for). I don't have a track interface on our end, but maybe there are other ways to solve the issue.

**Comment by marjohn56** [comment]
OK, only a suggestion.. I'll delete it.

**Comment by AdSchellevis** [comment]
I don't mind keeping it open for a while if it helps pinpoint the issue better, unfortunately I can't reproduce this myself.

**Comment by marjohn56** [comment]
OK, perhaps I didn't explain it very well. What appears to happen is that when the system comes up OR the dhcp6c client gets a change then when a  'dhcp6 configure' fires it's picking the VIP address if its already there, and it is already there, you only have to look at the dhcp6 server interface, it has the VIP address in it. So all this does is remove that alias, and it checks to see if it is an alias and removes it whilst it configures dhcp6c and then puts it back. The result being that dhcp6 then sets itself using the correct addresses and not the alias. It also makes sure the alias is re-applied. There is one extra check I can add, to make sure the alias is in fact a v6 address. If the interfaces is already in a configure state then this should have no side effects. Easy to test, all you need is a second router that slaves off a primary using dhcp6 track, the error shows up instantly as soon as you reboot the slave.

**Comment by marjohn56** [comment]
Cannot re-open this one now as I've cleaned and reset the repo, but I can re-issue it with that further check to make sure the alias is v6.

**Pull request closed without merging**
