### PR TITLE
opnsense original theme - sidebar hover update

### PR DESCRIPTION
**Pull request by opnsenseuser**
opnsense original theme - sidebar update

### CODE REVIEW

**Comment by opnsenseuser** [comment]
@marjohn56 
@fichtner 
@fabianfrz 
the same problem is here!
34 files that not belong to this pr. how can i get them away?

**Comment by opnsenseuser** [comment]
same here - will make it again! -> terrible mess!

**Comment by marjohn56** [comment]
Ok.. remember, when you update a branch, do a squash on the commits. That way you should stay out of trouble.

**Comment by opnsenseuser** [comment]
@marjohn56 
I have learned again! :-(
thx for your great support again!

**Pull request closed without merging**
