### PR TITLE
fix: move color settings from firewall_schedule_edit.php to theme

### PR DESCRIPTION
**Pull request by fabianfrz**

### CODE REVIEW

**Comment by marjohn56** [comment]
OK. Will do so when it's merged and I can test.

**Comment by marjohn56** [comment]
I have to take a look also at René's themes, he has forwarded them to me to PR, I'll try and do all three over the next few days.

**Comment by fichtner** [comment]
thanks. but merge conflict ?

**Comment by fabianfrz** [comment]
@fichtner you changed the same line in the file - it is already fixed. If you do a squashed merge, it will be gone.

**Comment by fichtner** [comment]
You're right, thanks for the hint and the submission. 👍

**Comment by fabianfrz** [comment]
@fichtner which sass do you use for compiling, because it changed so many lines by moving brackets?

```bash
sass -v
Sass 3.5.5 (Bleeding Edge)
```

**Comment by fichtner** [comment]
it was @AdSchellevis's change, don't know

**Comment by AdSchellevis** [comment]
```
sass --version
1.3.2
```

**Comment by AdSchellevis** [comment]
https://sass-lang.com/dart-sass seems to be the primary implementation, which is what homebrew installs

**Comment by fabianfrz** [comment]
OK, I use the ruby one: https://sass-lang.com/ (reference implementation)

**Comment by fabianfrz** [comment]
update: it was it, now it seems to be unmaintained for the dart one.

**Pull request merged**
