### PR TITLE
Firewall: switch for all custom rules logging

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi!
for possible discussion of the https://github.com/opnsense/core/issues/5219
thanks!

### CODE REVIEW

**Comment by fichtner** [comment]
Oh,this can and will quickly kill the whole system on large traffic volumes and/or fill up the disk completely. Selective logging per rule is a lot better and safer. Needle in haystack search is another issue here coupled with enormous noise generated.

**Comment by kulikov-a** [comment]
@fichtner completely agree that this opens up a shortcut to killing the system (and using the live log to find a triggered rule will only speed up the process). on the other hand, if an administrator decides to kill the system by debugging traffic this way on a production system during a high load period, he will successfully do it manually by enabling logging on all the rules that he can reach )
perhaps the compromise would be to add a confirmation popup (with an additional warning) before enabling the option?
__
I really don't see it as a lifesaving feature (but only as useful in certain circumstances, like https://github.com/opnsense/core/issues/3124). if you and @AdSchellevis  think this option is too dangerous, I will close requests immediately )

**Comment by AdSchellevis** [comment]
I'm not really a fan of this either to be honest, there's some relation to the discussion we had earlier about being able to feed all to an external log target (https://github.com/opnsense/core/issues/5191), but the scope of doing this properly is a lot wider and not really on our priority list. (one could question if filterlog shouldn't be ditched in the same pass and if the current format is suitable enough for external consumers for example)

**Comment by kulikov-a** [comment]
@fichtner @AdSchellevis understood, thanks)
closing requests as not useful

**Pull request closed without merging**
