### PR TITLE
OpenSSL: add keyUsage extension in CA config

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi!
ref. and hopefully closes https://github.com/opnsense/core/issues/5912
Thanks!

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@kulikov-a thanks, I think this would be a good addition indeed, since this only affects new CA's I don't think this has a very high impact, as this seems to be the advised setting anyway. Looking at https://openssl-ca.readthedocs.io/en/latest/intermediate-configuration-file.html and some other references, apparently the basicConstraints should append critical too (`basicConstraints = critical, CA:true`), what's your take on that?

**Comment by kulikov-a** [comment]
@AdSchellevis Thanks!
yes, reading (https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.9):
`
  Conforming CAs MUST include this extension in all CA certificates
   that contain public keys used to validate digital signatures on
   certificates and MUST mark the extension as critical in such
   certificates.
`
Im pretty sure that `basicConstraints = critical, CA:true` is the right choice. but there is a comment:
`# This is what PKIX recommends but some broken software chokes on critical
# extensions.` 
so i decided it was intentional and well reasoned

**Comment by AdSchellevis** [comment]
@kulikov-a I read the same note as well, no clue if this is still relevant to be honest, but let's keep it as is for now until someone opens a ticket.

**Comment by AdSchellevis** [comment]
@kulikov-a I'm not surprised, if we are going to change defaults anyway, we might as well change this one while there.

**Comment by kulikov-a** [comment]
@AdSchellevis yes, i would change it now if we try to follow the rfc in other places anyway and there are no reasoned objections. should i make a pr for this?

**Comment by AdSchellevis** [comment]
@kulikov-a yes please :)

**Pull request merged**
