### PR TITLE
Update temperature.sh for smaller CPU footprint 

### PR DESCRIPTION
**Pull request by meyergru**
Update temperature.sh for smaller CPU footprint
This patch eliminates many lines of output from sysctl and searches it much faster, because there is no regex matching.

This results in a smaller CPU footprint, thus reducing the impact of temperature monitoring itself on the reported temps, without changing the outcome.

See also: https://forum.opnsense.org/index.php?topic=36234.0

### CODE REVIEW

**Comment by fichtner** [comment]
Sorry, no. It just discards values for other people.

**Comment by meyergru** [comment]
Like which? The code analysing the output even filter on hw.acpi....

**Comment by fichtner** [comment]
For reference: f473d9a5c74e

**Comment by fichtner** [comment]
> Like which? The code analysing the output even filters on hw.acpi....

It does not filter, it separates the Zone and CPU cases (which is also too optimistic).

**Comment by meyergru** [comment]
I never saw any temperatures in sysctl besides hw.acpi and dev.cpu - though that does not mean they do not exist.

**Pull request closed without merging**
