### PR TITLE
add lodash.js

### PR DESCRIPTION
**Pull request by fabianfrz**
required for building templates running client side and messing with objects and arrays

### CODE REVIEW

**Comment by fabianfrz** [comment]
@fichtner If you are going to do a release this week, don't forget about this as it will break the quagga plugin if missing.

**Comment by fichtner** [comment]
just master or both? hoping for a ok from @AdSchellevis (seems no need to add this to the default template)

**Comment by fichtner** [comment]
https://github.com/opnsense/plugins/commit/e273ba6f491dddc30b59c166e558f8cc08fcab41 makes more sense to me ;)

**Comment by fabianfrz** [comment]
will do it too - hoped to include it in core so it would be shared between plugins and could be used for refactoring of pages. However the impact is minimal as the paths are the only thing that needs to be adjusted in such a case.

**Comment by AdSchellevis** [comment]
@fichtner we could always add it to core later if if we're going to use it anywhere else, although having a directory for the plugin itself is probably the best for now.

**Pull request closed without merging**
