### PR TITLE
Shaper: Add DSCP matching

### PR DESCRIPTION
**Pull request by mimugmail**
There was a request on Friday if we support DSCP matching for shaper. @fichtner and me said no, only for `pf` but then I checked ipfw manpage and it looks good.
The beauty of this is, that you can have multiple rules with match any any as you can match for differenct DSCP values, mostly set by SIP phones automatically. Would be a nice addition for enterprise demands.
If pf acts before ipfw in shared forwarding you could also mark rules with pf for DSCP and do the shaping afterwards :)

### CODE REVIEW

**Comment by muchahagrande** [comment]
Would be "THE SOLUTION" I was expecting for.

**Comment by mimugmail** [comment]
Sounds like a volunteer for beta testing :)

**Comment by muchahagrande** [comment]
Hehe... sure... I can do it.

**Comment by AdSchellevis** [comment]
@mimugmail thanks, the ruleset looks decent, I haven't tried the feature itself, but when in master it's easier for others to do more testing.

**Comment by mimugmail** [comment]
@AdSchellevis thanks for merge!
@muchahagrande can you test this with current master?

**Comment by muchahagrande** [comment]
Excuse my ignorance on the subject... may be I'm gonna ask a couple of stupid questions.
As I have OPNSense virtualized on ESXi, I've created a copy of my router to do the testing.
The first thing I did is switching to development branch. Not sure if it is the rigth step.
But I cant find the new dialog in traffic shaper rules menu.
How can I test with the current master?

**Comment by fichtner** [comment]
# opnsense-code core
# cd /usr/core
# make upgrade

**Comment by muchahagrande** [comment]
Ok, in the "make upgrade" it stopped with the following error:

...
...
All repositories are up to date.
pkg: No packages available to install matching 'squid' have been found in the repositories
*** Error code 70

Stop.
make: stopped in /usr/core

I still cant find DSCP options in traffic shapper

**Comment by mimugmail** [comment]
@muchahagrande 
make upgrade CORE_SQUID=3

Then you'll see it :)

**Comment by muchahagrande** [comment]
With "make upgrade CORE_SQUID=3" the upgrade went OK.
But I still can't see DSCP options in shaper menu :-(

**Comment by mimugmail** [comment]
@muchahagrande in rules you have to tick "advanced" to see the dropdown multiselect.

**Comment by muchahagrande** [comment]
It it ticked...
May be something went wrong with the update process.
Going to try it again with a fresh restored virtual machine.
Additionally, after the upgrade and a reboot, I couldn't login with SSH anymore.

**Comment by muchahagrande** [comment]
Great... beggining from a fresh VM backup did the trick.

Before I got "OPNsense\TrafficShaper\TrafficShaper 1.0.2"
Now I see "Migrated OPNsense\TrafficShaper\TrafficShaper from 1.0.2 to 1.0.3"

I can see DSCP option on traffic shaper rules.
I'll do some testing trying to separate my PBX traffic from the ordinary one.

**Comment by muchahagrande** [comment]
Is there an accurate diagnostic for IPFW ?
With the slow refresh of the traffic shaping status I can't be sure of the results of my testing.

**Comment by mimugmail** [comment]
Create 3 pipes, all rule match any any but different dscp. The start a vioce call and you should see matching traffic for this pipe. The switch the value to other pipes to check against

**Comment by muchahagrande** [comment]
I made two pipes one for 8 Mbit and the other for 2 Mbit.
I created two rules on WAN with outgoing direction and matching any any.
The first rule with DSCP=CS3 using the 2 Mbit limiter for VoIP and the second without DSCP using the 8 Mbit pipe for the rest of the traffic.
The first rule is catching all the traffic and sending it through the 2 Mbit pipe like it were ignoring the presence of the DSCP attribute.
I made a speedtest and it's limiting my upload to 2 Mbit when it should be 8 Mbit using the second rule.

**Comment by mimugmail** [comment]
I'll try to reproduce :/

**Comment by mimugmail** [comment]
Sidenote:

@AdSchellevis @fichtner @fabianfrz 
This comes when updating to latest master in system.log:

`Mar  1 12:45:48 OPNsense /configd.py: Handler died on Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 87, in run     config_environment=self.config_environment)   File "/usr/local/opnsense/service/modules/__init__.py", line 37, in getinstance     instances[cls] = cls(*args, **kwargs)   File "/usr/local/opnsense/service/modules/processhandler.py", line 255, in __init__     self.load_config()   File "/usr/local/opnsense/service/modules/processhandler.py", line 272, in load_config     cnf.read(config_filename)   File "/usr/local/lib/python3.6/configparser.py", line 697, in read     self._read(fp, filename)   File "/usr/local/lib/python3.6/configparser.py", line 1066, in _read     lineno) configparser.DuplicateSectionError: While reading from '/usr/local/opnsense/service/conf/actions.d/actions_nginx.conf' [line 35]: section 'log' already exists
`

**Comment by AdSchellevis** [comment]
@mimugmail configd is right here :) https://github.com/opnsense/plugins/blob/127fe3ddfebd8980321f656bfcf90f2fe8a1cc3b/www/nginx/src/opnsense/service/conf/actions.d/actions_nginx.conf#L29-L39, something for @fabianfrz to fix

**Comment by mimugmail** [comment]
@muchahagrande can you fetch latest master and try again .. thx to @AdSchellevis it's working now.
Previously the line in config was:

add 60001 pipe 10000 ip from any to any src-port  any dst-port any    dscp ['af11', 'af21'] via em0 // wan: pipe1

and since this is wrong ipfw just replace it with best effort. Now it's working fine on my end.

**Comment by fichtner** [comment]
nice, this means hotfix nginx plugin -.-

**Comment by fichtner** [comment]
ah, nevermind... this is a new Python 3.6 error it seems so we don't have to hotfix... :)

**Comment by AdSchellevis** [comment]
it's not an issue with python, it could be that python 2 was a bit more forgiving in this regard, but duplicating sections isn't a guarantee to success :)

**Comment by muchahagrande** [comment]
@mimugmail what's the command to fetch the master?

**Comment by fabianfrz** [comment]
opnsense-patch

**Comment by muchahagrande** [comment]
@mimugmail, after a couple of tests I can confirm that is working fine.
I made two pipes for upload, one for 2 Mbit and the other for 8 Mbit. The sum of both is the total upload bandwidth I can get from my ISP.
Then I made two rules to redirect VoIP traffic through the first pipe and the rest through the second one.
The filter criteria to catch the PBX traffic was only DSCP=Expedited Forwarding,AF41,CS3 that corresponds to voice, video and sip packets.
I made some calls and I saw packets passing through the 2 Mbits pipe. After that I made a speed test and the upload was limited to 8 Mbits using the second pipe.
Finally I made a speed test while making a call, and both traffics were conducted through their respective pipes giving a clean voice without interruptions.

I think that ipfw with DSCP is working as expected.

**Comment by muchahagrande** [comment]
@mimugmail 

> If pf acts before ipfw in shared forwarding you could also mark rules with pf for DSCP and do the shaping afterwards :)

Do pf rules already support marking packets with DSCP?

**Comment by mimugmail** [comment]
Yes, just look at the rules, but I'm unsure If marking happens before ipfw. @fichtner ?

**Comment by muchahagrande** [comment]
I think that the marking matched and set on the pf rules page referes to 802.1Q VLAN header that happens at ethernet level, but DSCP is another ToS marking that hapens at IP header level. To use DSCP at the pf rules page there should be some combo boxes to match/set DSCP in addition to the ones that are already there.

**Pull request merged**
