### PR TITLE
Added check on SNI field checkbox

### PR DESCRIPTION
**Pull request by Northguy**

### CODE REVIEW

**Comment by fichtner** [comment]
it might be better to solve this with a proper constraint that can automatically generate the error if the settings don't align properly

**Comment by Northguy** [comment]
Agree, but don't know how to do that... ;-) If you can point me in the right direction where this has been done on other fronts, I can copy paste... but i am too novice to code a resolution for this myself.

**Comment by fichtner** [comment]
You can do it :) take a look at https://github.com/opnsense/plugins/commit/ba2f306ab7359b6121339952d3c4e1ebb95ee125#diff-56136ef67398545535eb99e9ba6af9f4

**Comment by Northguy** [comment]
> You can do it :) take a look at [opnsense/plugins@ba2f306#diff-56136ef67398545535eb99e9ba6af9f4](https://github.com/opnsense/plugins/commit/ba2f306ab7359b6121339952d3c4e1ebb95ee125#diff-56136ef67398545535eb99e9ba6af9f4)

OK, thanks @fichtner. After some experimenting and checking other code, I managed to build in a dependency check. Still strugling a lot with the basics of committing and such, but managed to check my own work with opnsense-patch .... "hurray".... Ready for merging.

On a sidenote: 
I tried using Gitkraken to work locally on my PC, but ran into editor issues. The editor does not convert tabs to spaces unfortunately. Any tips on a good integrated Git client with editing possibilities?

**Comment by fichtner** [comment]
@Northguy nice work, thanks!

I'm not sure about good editors, especially the ones that have built-in git support. They tend to make a mess of branches, spurious merges, etc. It's better to learn the basics for git (especially branching and rebase for tidy PRs) or edit directly on GitHub as an alternative.

**Comment by Northguy** [comment]
OK, so Git desktop and Notepad++ would be the better alternative?

**Comment by fichtner** [comment]
I guess so, although there are some nicer IDEs out there, but I wouldn't know which.

**Comment by mimugmail** [comment]
I'm using N++ and GH Desktop too, for small changes only GitHub.com

**Comment by fabianfrz** [comment]
@fichtner I am working with PHP Storm which has a good git client.

**Pull request merged**
