### PR TITLE
inline nmea checksum calculator; use bootstrap style for button

### PR DESCRIPTION
**Pull request by fabianfrz**
This was probably not planned that bootstrap breaks the line before and after the input field. Also the button was missing bootstrap style.

screenshot_20180207_190737

### CODE REVIEW

**Comment by fichtner** [comment]
Looks like we could get get rid of the leading "$" and trailing "*checksum" as it says so in the label?

**Comment by fabianfrz** [comment]
@fichtner the "checksum" string will be replaced by the checksum after the button is pushed so it cannot be removed.

**Comment by fabianfrz** [comment]
now looks like this:
screenshot_20180208_173140

and the advanced button has been formatted too:
screenshot_20180208_173222

**Comment by fichtner** [comment]
Thanks, I'll take a look on the offset of text and button in the morning.

**Pull request merged**
