### PR TITLE
Multiple Type DHCPv6 DUID support and generation.

### PR DESCRIPTION
**Pull request by marjohn56**
As it says, it's also possible to just use the  dhcp6c restart button just to re-fire that on its owm.

### CODE REVIEW

**Comment by marjohn56** [comment]
Just noticed there's a stray '$wanif = get_real_interface('wan', "inet6");' which needs removing. It's a leftover from a direction I was taking to get the MAC address, changed my mind and went a different route.

**Comment by marjohn56** [comment]
Because the length of the DUIDs can be up to 128 chars, the manual entry "input" needs to be changed to a textarea, I can get that working, what I am having issues with is updating the textarea on the 'onclick' event in help field.

**Comment by fichtner** [comment]
Works from here if I manually change the &lt;input/> to &lt;textarea>&lt;/textarea>. Maybe you want to push the "faulty" change for closer inspection.

**Comment by marjohn56** [comment]
OK, gimme two.

**Comment by marjohn56** [comment]
Line 466.. This is obviously wrong as it does not work. I've tried various ways of doing it but no joy. Do I need to create a function?

**Comment by fichtner** [comment]
don't delete the attribute id= and it will work

**Comment by marjohn56** [comment]
example por favour.. :)

**Comment by fichtner** [comment]
huh :D like this...

    <textarea name="ipv6duid" id="ipv6duid" rows="2" ><?=$pconfig['ipv6duid'];?></textarea>

**Comment by marjohn56** [comment]
Nay :) You're not reading what I have written. The textarea at 464 is fine, it's the onclick event at line 466, used to dynamically update the textarea with the read_duid() function. This will not work for example, although I read various web postings saying it should or should not.

`<a onclick="$('#ipv6duid').val('<?= read_duid() ?>');" href="#"><?=gettext("Insert the existing DUID here"); ?></a>`

**Comment by marjohn56** [comment]
Still cannot get it to work...

**Comment by fichtner** [comment]
```
--- /usr/local/www/system_advanced_network.php.orig	2018-08-05 14:10:20.911241000 +0200
+++ /usr/local/www/system_advanced_network.php	2018-08-05 14:11:32.016932000 +0200
@@ -461,9 +461,9 @@
               <tr>
                 <td><a id="help_for_persistent_duid" href="#" class="showhelp"><i class="fa fa-info-circle"></i></a> <?=gettext("Stored DHCP6 Unique Identifier"); ?></td>
                 <td>
-                  <textarea name="ipv6duid" rows="2" ><?=$pconfig['ipv6duid'];?></textarea>            
+                  <textarea name="ipv6duid" id="ipv6duid" rows="2" ><?=$pconfig['ipv6duid'];?></textarea>            
                   <div class="hidden" data-for="help_for_persistent_duid">
-                  <a onclick="$(pconfig['ipv6duid']('<?= read_duid() ?>');" href="#"><?=gettext("Insert the existing DUID here"); ?></a>
+                  <a onclick="$('#ipv6duid').val('<?= html_safe(read_duid()) ?>');" href="#"><?=gettext("Insert the existing DUID here"); ?></a>
                     <?= gettext('<br>This field can be used to enter an explicit DUID for use by IPv6 DHCP clients.<br>
                         The correct format for each DUID Type is as follows, all entries to be in hex format "xx" seperated by a colon.<br>
                         LLT: 4 bytes "00:01:00:01" followed by 4 bytes Unix time e.g. "00:01:02:03", followed by six bytes of the mac address.<br>
```

**Comment by marjohn56** [comment]
And it doesn't work for me. :)

**Comment by marjohn56** [comment]
Yes I was.. fixed... Ta muchly.

**Comment by marjohn56** [comment]
bump.

**Comment by fichtner** [comment]
@marjohn56 I spent 3 hours breaking this down due to workflow and style concerns. Ended up rewriting the proposed integration in what is about half of what was originally added in code. It's not perfect yet, but it's a step forward. It does take a lot longer to merge if hours have to be spent reviewing / reworking so I wanted to stress that point.

**Pull request closed without merging**
