### PR TITLE
Large CPU widget

### PR DESCRIPTION
**Pull request by marjohn56**

### CODE REVIEW

**Comment by marjohn56** [comment]
Large CPU Widget ref #2292

**Comment by fichtner** [comment]
Merged, thanks. Need another file and a fixup for the plist, follows in a second. :)

**Comment by marjohn56** [comment]
What's the plist for and where and what needs doing to it... and why is Donald Trump president of the USA.... so many questions, so little time..

**Comment by fichtner** [comment]
plist is for QA purpose, it lists all files that the repo installs:

    # make plist

or

    # make plist-fix

**Comment by marjohn56** [comment]
Ah, understood, Should I have adjusted that or is that down to your good self?

**Comment by fichtner** [comment]
If new files are added or deleted it's ok to push it with the PR, "make upgrade" installs the current git state in the system and does all the sanity checks so it tells you if e.g. plist fails

**Comment by fichtner** [comment]
(of course, that only works in a live system)

**Comment by marjohn56** [comment]
I see it...

**Pull request merged**
