### PR TITLE
sidebar - refresh optimization last fix

### PR DESCRIPTION
**Pull request by opnsenseuser**
i can´t get all code optimizatied (please it´s important to merge this, because of big trouble with scrolling) - no more fixes after this needed. sorry

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@opnsenseuser no problem, things happen, maybe we should leave this on master for some time for further testing.

**Comment by opnsenseuser** [comment]
@AdSchellevis no. it really works now. Please release it in the next version. thx for your support 👍

**Comment by opnsenseuser** [comment]
@fichtner is it possible to go live with this update with the next patch day? regards rené

**Comment by fichtner** [comment]
@opnsenseuser I’d like to kindly ask you to stop asking this particular question for each of your submission. Thank you.

**Pull request merged**
