### PR TITLE
Proposal fix issue #848

### PR DESCRIPTION
**Pull request by thelinuxfr**
Proposal fix issue #848

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@thelinuxfr the idea is good, but it should be fixed in the sass file (main.scss) with an override and then be compiled into the css file again.
This css stuff is a bit magic from time to time, the idea of the bootstrap components is that you use the standards and extend them where needed, but I can't guarantee that none of the files are changed at the moment. (but I would try to minimize changes to standards where possible)
Need help with creating the override?

**Comment by thelinuxfr** [comment]
@AdSchellevis I modified the scss, I will help in the following

**Comment by AdSchellevis** [comment]
@thelinuxfr I checked the issue again with your fix, your fix functions perfectly, but should only apply to this type of dropdown box.
What about his fix https://github.com/opnsense/core/commit/b32d93da219b025387ca005b02fcb1e5c23514fb ?

**Comment by fichtner** [comment]
FWIW, I've seen such intentional behaviour on iOS to indicate that there is more data in the box as opposed to rendering it "correctly" where it's not clear that there is more entries after the last one. I do not think this has to be a bug.

**Comment by AdSchellevis** [comment]
I don't have a strong opinion on this one, both work for me, I'm happy to revert the change if  the slightly cut-of version seems more obvious for people.

**Comment by thelinuxfr** [comment]
I test tomorrow, but your solution seems correct , I would close my PR if it's ok

**Comment by thelinuxfr** [comment]
@AdSchellevis Fix your suits me, it is true that this introduces another problem when there are only two elements ... I closed my PR

**Comment by AdSchellevis** [comment]
@thelinuxfr the fix might not make it into the release because of other issues, see https://github.com/opnsense/core/issues/848

**Pull request closed without merging**
