### PR TITLE
radvd: Added option to set DeprecatePrefix to off

### PR DESCRIPTION
**Pull request by vlcty**
I added an option to radvd to disable prefix deprecation. This refers to issue #4328 .

Bildschirmfoto 2020-09-06 um 20 27 20

### CODE REVIEW

**Comment by AdSchellevis** [comment]
There's probably no perfect fix for this, but since DeprecatePrefix is influenced by more toggles, the meaning can be confusing.

https://github.com/opnsense/core/blob/2cff1c5f12fab71e3baa2a03fd82c1bcfeb7d5b3/src/etc/inc/plugins.inc.d/dhcpd.inc#L330

https://github.com/opnsense/core/blob/2cff1c5f12fab71e3baa2a03fd82c1bcfeb7d5b3/src/etc/inc/plugins.inc.d/dhcpd.inc#L497-L501

https://github.com/opnsense/core/blob/2cff1c5f12fab71e3baa2a03fd82c1bcfeb7d5b3/src/etc/inc/plugins.inc.d/dhcpd.inc#L508-L525

Let's try to collect some feedback before pulling this in. Unfortunately some legacy things are hard to change without risking behavioural differences for other users.

**Comment by fichtner** [comment]
I thought about this... if the user knows the prefix is static it should be able to override the deprecation. The patch needs cleanup but there's no harm providing a manual toggle for those who know what they are doing. But this only counts for manual radvd mode anyway.

**Comment by fichtner** [comment]
As another way around this we could just offer "rainterface" with a dynamic and static mode (currently it is only shown as carp interface list). It already does move everything to "sticky" mode, also the route lifetime...

**Comment by fichtner** [comment]
@vlcty does this work for you? b5b2b213fcc429cd1d3

**Comment by vlcty** [comment]
Yeah that'll also work for me. I think it's actually a more elegant way to solve it.

**Comment by fichtner** [comment]
ok, thanks! I'll leave the ticket open to do some GUI option rewording for rainterface. If you have a suggestion there feel free to create PR :)

**Pull request closed without merging**
