### PR TITLE
Move settings for dhcp6c to system_advanced_network

### PR DESCRIPTION
**Pull request by marjohn56**
To go with #4088

### CODE REVIEW

**Comment by fichtner** [comment]
Thanks!

**Comment by marjohn56** [comment]
line 480 in dhcpd, I made the comment that it barfs radvd.. need to look at that.

**Comment by fichtner** [comment]
I remember, bring on the last PR dear Sir.

**Comment by marjohn56** [comment]
It would seem that's already been fixed, so it's some testing that now needs to be done. I suggest we post a forum message looking for users who want to test multiwan dhcp6.

**Comment by marjohn56** [comment]
Ooerr... only one rtsold script... hmm, dat won't work. :)

**Comment by fichtner** [comment]
Why not? Same config, same PID, same debug/norelease.

**Comment by marjohn56** [comment]
Yup sorry... brainfart moment... I'm wondering why I'm not seeing multiple routes... I'll find it.

**Comment by marjohn56** [comment]
interfaces - rtsold should be passed all the interfaces, otherwise it will only get the info from the one given.

**Comment by fichtner** [comment]
Merged via 5ed15ca, thanks! ❤️

**Pull request closed without merging**
