### PR TITLE
New IPSec configuration interface: XAuth PAM (group) constraints

### PR DESCRIPTION
**Pull request by GottemHams**
With the legacy interface we could restrict mobile users (or more likely, PAM auth in general) to certain groups. Since the new interface has you enabling XAuth on an individual remote authentication round, it makes sense to also have related settings somewhere in the vicinity. I chose a separate subtab under `Connections [new]`, since these **do affect all auth attempts** that go through Strongswan's `xauth-pam` plugin (`libcharon`'s actually though), similar to what it originally does. I did notice `swanctl.conf` allows a `groups` directive for the remote auth round, which could allow for round-specific group constraints. Unfortunately though, after messing around quite a bit with OPNsense's PAM module it seems like XAuth in general doesn't really support groups on its own. ;_;

The new-style VPN settings will take precedence over legacy ones (in some places) to try and avoid conflict. Of course this isn't 100%, since if you configure a legacy phase 1 or phase 2 then I've allowed OPNsense to still insert some config in `swanctl.conf`. But due to the overlap with the legacy mobile client settings I did make it skip a fair portion of it for **strongswan.conf**. It should still be possible to configure a VPN connection through the new interface in such a way that mobile clients can connect too. The original mobile settings are kinda insecure anyways I think, so this might even help move people to more secure settings (the new method doesn't insert any phase config itself, it only configures `charon` to interact with PAM).

Furthermore, the constraints shouldn't conflict with auth methods that aren't XAuth, since `charon` only uses OPNsense's `IPsec` auth service specifically when it's told to use the `xauth-pam` plugin. RADIUS, EAP, etc all have their own plugins so no problems there. :>

**Do note though** that I also mirrored the auth database setting, although I'm not entirely sure what the implications of it are. In my case I only have the local DB, but choosing something different might not even be relevant?

### CODE REVIEW

**Comment by AdSchellevis** [comment]
Have you tried to just use the settings in "VPN: IPsec: Mobile Clients"? I don't really see a reason why the existing mobile settings wouldn't apply here (if they don't, we should probably aim for investigating that first).

**Comment by GottemHams** [comment]
They do, but the main problem with those is that you can't **just** enable the XAuth settings, it also adds phase configuration. The way the new interface is set up kind of makes those settings redundant, so I figured it was meant to replace the legacy phase configuration plus the accompanying mobile settings in their entirety.

**Comment by AdSchellevis** [comment]
ok, then we better fix the issue with the legacy page first, both will be here for some time, better to aim for consistency here. If you open a ticket, I don't mind taking a look at how we can do that in a most practical way (minimizing code)

**Comment by GottemHams** [comment]
Works for me, by ticket I assume you mean a regular issue here on GitHub? :>

**Comment by AdSchellevis** [comment]
yes please, I'll try to look at it asap, it really helps if there's someone to test in these cases

**Pull request closed without merging**
