### PR TITLE
Fix #2960: Limit line length in log widget

### LINKED ISSUE #2960: system log widget - lines limiting?
in my opinion, the lines should be limited, because the user can anyway come at any time with a click in the detail view of the system logs. And so on the dashboard would also allow a much clearer presentation. and it would not turn out to be an endless line view as I have stated in my screenshot.

grafik

### PR DESCRIPTION
**Pull request by MichaelDeciso**
For consistency, I added the line char limit parameter to both `dump_clog` and `dump_log`.

### CODE REVIEW

**Comment by opnsenseuser** [comment]
@MichaelDeciso 👍 

https://github.com/opnsense/core/issues/2960

**Comment by MichaelDeciso** [comment]
@opnsenseuser Have you been able to test it? Does it work for you?

**Comment by opnsenseuser** [comment]
@MichaelDeciso  will Test this in a few hours and will give you Feedback on this.

**Comment by opnsenseuser** [comment]
@MichaelDeciso i can´t see any real difference . i just replaced the two files with your new ones. i also deleted the browser cache. but i can´t see any difference.

this is a short screenshot
widget_log_before

**Comment by opnsenseuser** [comment]
@MichaelDeciso i think it would be better to Limit the line breaks and not the sum of the characters. But thats only my opinion. Regards rene

**Comment by opnsenseuser** [comment]
@MichaelDeciso I have still come up with an idea. 
limit the lines and at the end of a sign with which you can open the entire entry (only if the user wants to see the entire text).

**Comment by opnsenseuser** [comment]
@MichaelDeciso yes, in a few Hours!

**Comment by opnsenseuser** [comment]
@MichaelDeciso i tested again and cleared the browser cache too. but this time the system log is completely empty! 

grafik

**Comment by opnsenseuser** [comment]
@MichaelDeciso you did it! 👍 

grafik

**Pull request merged**
