### PR TITLE
traffic shaper: add a ! for negated fields

### PR DESCRIPTION
**Pull request by fabianfrz**
probably not the cleanest solution but it works. -> ticket #2004 

bildschirmfoto am 2017-12-19 um 19 06 58

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@fabianfrz not bad at all, thanks!

**Comment by fabianfrz** [comment]
@AdSchellevis not sure if I can get the json out of it.

**Comment by AdSchellevis** [comment]
@fabianfrz I see what you mean, let me try something

**Comment by AdSchellevis** [comment]
@fabianfrz here you are https://github.com/opnsense/core/commit/78686814a472df4a9cce69ee15b7f31d9cf1ffa2 , you can easily ditch the json conversion because the object is send to the conversion function.

**Comment by fabianfrz** [comment]
@AdSchellevis this will be probably a requirement for the firewall sections too when the migration will start.

**Comment by AdSchellevis** [comment]
@fabianfrz I'm not sure bootgrid will be good enough to restructure the firewall section, but we'll see

**Pull request merged**
