### PR TITLE
Dev/ipfwcaptiveportal

### PR DESCRIPTION
**Pull request by fredronnv**
I think this relates to #3089. I noticed that captive portal wasn't working unless I explicitly added the CARP VIPs to the "Allowed addresses" list.
This PR makes all VIPs on captive portal interfaces allowed by default by changing the template for ipfw.conf. I needed an extra array in cp_interface_list to allow checking against the if later.

Only VIPs on Captive Portal interfaces are added, in the same manner as "Allow traffic to this hosts static ip's".

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@fredronnv thanks, I have to check this, at a first glance the only issue seem to be that the client can't reach the vip interface (for dns / icmp), right? In that case could probably also bind the rules to the physical interface, which reduces the number of rules.

**Comment by fredronnv** [comment]
@AdSchellevis yes, you're right, that's the reason. No DNS resolutions on captive portal if you've configured the VIPs for that purpose. I'll get a commit sorted to bind the rules to the physical interface as well.

**Comment by fredronnv** [comment]
@AdSchellevis actually, looking at it, I think really only DNS is needed to make it work, really, so could limit it to that only. I'll test it out.

**Comment by AdSchellevis** [comment]
you could probably change the `ipaddr` for `if` in the original line

```
add {{loop.index  + 1000}} skipto 60000 udp from any to {{ interface.ipaddr }} dst-port 53 keep-state
```

**Comment by AdSchellevis** [comment]
`to me ` seems to to the trick https://www.freebsd.org/cgi/man.cgi?ipfw(8) and add a `via`  at the end

**Comment by fredronnv** [comment]
Ah I see what you mean, that's probably preferrable. I'll make the necessary changes.

**Comment by AdSchellevis** [comment]
@fredronnv Thanks! very nice to have you around here

**Comment by AdSchellevis** [comment]
we could probably move the full block of rules into your new construction, logically the same also counts for traffic out using the vip in these cases.

**Comment by fredronnv** [comment]
If you'd like I can rework it, but I need a bit of time to make there are no unexpected consequences. I've got some time tomorrow morning (CET) I can dedicate to this.

**Comment by AdSchellevis** [comment]
great! thanks in advance

**Comment by fredronnv** [comment]
Come to think of it, it's unnecessary to loop over interfaces if we use "to me", isn't it?

**Comment by AdSchellevis** [comment]
we should loop, since we only want the captive portal interface, don't want to risk opening udp 53 on wan :)

**Comment by fredronnv** [comment]
Of course, done.

**Comment by AdSchellevis** [comment]
@fredronnv thanks, I'll give it a spin here and pull it in later.

**Pull request merged**
