### PR TITLE
(ids) Fix display of the row count in the footer for alarm logs (Smart-Soft)

### PR DESCRIPTION
**Pull request by Sergey-Kirpa**

### CODE REVIEW

**Comment by AdSchellevis** [comment]
The rowcount is intentionally lazy, these files can grow rapidly and you really don't want to risk parsing 2G or more of log data. 
There might be more side affects in this, we shouldn't include this.

**Comment by Sergey-Kirpa** [comment]
I meant not a global record count but the number of records on a page. I will try to explain in steps.

1. Open the "Alert" tab on the "Services: Intrusion Detection: Administration" page

**Comment by L1ghtn1ng** [comment]
@AdSchellevis any traction on getting this merged?

**Comment by AdSchellevis** [comment]
@L1ghtn1ng we're not planning on merging this, Smart-Soft's PR's usually involve a lot of work on our end (for example https://github.com/opnsense/core/pull/3107 --> https://github.com/opnsense/core/issues/3399 ), for which they seem to believe others will pay (either in time or money). 

Which won't mean if there's an issue we're not going to solve it, we're just very cautious in accepting code from them for obvious reasons.

**Comment by L1ghtn1ng** [comment]
Fair enough
________________________________

**Comment by L1ghtn1ng** [comment]
@AdSchellevis Regarding this issue that this PR is trying to resolve can this not be done with the API to to use that number as when you query the API it gives you the total, if that is a feasible fix that could be done?

**Comment by AdSchellevis** [comment]
@L1ghtn1ng this https://github.com/opnsense/core/commit/06acf28ae5992957aaacab644863b150723d142f basically is the reason why I rather see a detailed issue report then a large block of code in a PR without context.... These things cost a lot of time to read and interpret, for which Smart-Soft expects others to pay.

**Comment by L1ghtn1ng** [comment]
Okay fair enough sorry

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AdSchellevis** [comment]
@L1ghtn1ng no problem

**Comment by Sergey-Kirpa** [comment]
> @L1ghtn1ng this [06acf28](https://github.com/opnsense/core/commit/06acf28ae5992957aaacab644863b150723d142f) basically is the reason why I rather see a detailed issue report then a large block of code in a PR without context.... These things cost a lot of time to read and interpret, for which Smart-Soft expects others to pay.

Unfortunately, this [06acf28] did not correct the error I described above. So the problem still remains. Do you really think that we have nothing more to do if we debug and fix bugs, and this is not worth anything to us?

**Comment by AdSchellevis** [comment]
It did fix the row count on my end, I'm also quite certain we don't have to change the world here to fix this issue. We value code quality a lot. I'm not saying we won't except any of your (Smart-Soft) changes, if small, easy to validate we'll likely do so. 

It has been made very clear to us that your company expects others to pay for the work needed to test, integrate and cleanse your work, which I personally am not planning to do. 

In the past we have had quite some issues with code delivered by your company, which did cost us a lot of time to fix afterwards (which obviously isn't free).

You're more than welcome to use our product any way you like, without any obligations, we on our end have the responsibility for all our users and guard our products code quality.

**Pull request closed without merging**
