### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gonzopancho**
insert a space in the obvious place

### CODE REVIEW

**Comment by fichtner** [comment]
I'm not going to accept your commits. Here's why.

You have been blocked on various OPNsense developer's Twitter accounts for excessive mentions and childish behaviour.

You interact with a known individual "htilonom" on a daily basis who seeks to destroy the reputation of our fork.

https://twitter.com/htilonom/with_replies

Both of you have shown utter lack of respect of boundaries on OPNsense-only topics on Reddit.

https://www.reddit.com/r/networking/comments/3tvanp/is_anyone_here_using_opnsense/

There are tens of other cases. You've gone too far. You're not welcome here.

**Comment by gonzopancho** [comment]
I guess a commit bit is out of the question, then?

**Comment by fichtner** [comment]
Yes, you got that right.

**Comment by gonzopancho** [comment]
https://pbs.twimg.com/tweet_video/CVvEj4qWUAEEdwe.mp4

**Comment by gonzopancho** [comment]
http://goo.gl/LnXmz9

**Pull request closed without merging**
