### PR TITLE
Add multiple interfaces to rtsold call

### PR DESCRIPTION
**Pull request by marjohn56**
We need to get all of the router info from rtsold so need to add multiple interfaces. Something like this, it works but maybe not the best way.

### CODE REVIEW

**Comment by fichtner** [comment]
Geez, why can't these daemons run in parallel? :(

So there is a "-a" option here. If we make sure we only fire dhcp6fc for interfaces that have a valid config around (we can check this as we use it pre-merge for dhcp6c.conf) that would suffice, no?

**Comment by marjohn56** [comment]
The daft thing is that if you read the rtsold(8) it sort of contradicts itself...  I've been going round in circles trying to figure out why I am getting the same route address for both my WAN interfaces... then it struck me, they are both VLANs off the same interface on the primary router!

OK, let me try the -a option, I assume that means we don't spec interfaces in the command?

**Comment by fichtner** [comment]
Yep, this and d8c8129889aa should prevent any non-expected fallout

**Comment by marjohn56** [comment]
-a option works, defaultgw6 and routerv6 are created for both my WAN interfaces.

**Comment by marjohn56** [comment]
I'll do a full test once you pull this in.

**Comment by fichtner** [comment]
Do you mean "pull this in" as in I add -a and close the PR, or do you want to amend this PR to include -a to be pulled in? :)

**Comment by marjohn56** [comment]
:) doing the changes now...

**Comment by marjohn56** [comment]
Argh.. this logging bug is £$%"%!!!! 

I THINK it's working OK. :)

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by fichtner** [comment]
Master is now at bc5405bd54cd, what do you think?

**Pull request merged**
