### PR TITLE
core/radvd - do not advertise DNS domain when DNS advertisments are disabled

### PR DESCRIPTION
**Pull request by pmhausen**
https://github.com/opnsense/core/issues/5919

### CODE REVIEW

**Comment by fichtner** [comment]
@pmhausen looks reasonable, maybe @maurice-w can weigh in as well

**Comment by fichtner** [comment]
Actually under the hood this is implemented as radisablerdnss which is correct in that it ignores DNSSL. it probably makes sense to merge this or alternatively make the setting more explicit in the GUI and add one for DNSSL as well. Both work for me, just need to make sure we document this in the code if we opt for this solution here (number 1).

**Comment by pmhausen** [comment]
Comments added, squashed commit.

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by pmhausen** [comment]
Geez ... you are quick. I just did the UI reorganising as suggested by @maurice-w ...

New pull-request?

**Comment by fichtner** [comment]
sure but please wait for my dhcpd.inc change

**Pull request merged**
