### PR TITLE
fix link to development architecture

### PR DESCRIPTION
**Pull request by cwildfoerster**
noticed a dead link in the readme, fixed it

### CODE REVIEW

**Comment by fichtner** [comment]
Nice catch, thanks! Can you make it https://docs.opnsense.org/development/architecture.html -- "wiki" is the legacy link :)

**Comment by cwildfoerster** [comment]
@fichtner done. glad i could help just a little bit. hope i can get my development environment running in the future, i would like to start creating plugins... maybe

**Comment by fabianfrz** [comment]
@cwildfoerster for plugins you just need the `plugins` repository.
for an example, see: https://docs.opnsense.org/development/examples/helloworld.html

**Comment by fichtner** [comment]
@cwildfoerster thanks! just ping us if you need help with plugins, we are happy to help :)

**Pull request merged**
