### PR TITLE
firewall log widget: multiple interface choice, popovers, link to Live View

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi!
replaces https://github.com/opnsense/core/pull/4817 and possibly closes https://github.com/opnsense/core/issues/4815
- no `legacy_config_get_interfaces`
- multiple choice of interfaces
- no `toLowerCase()`
- not reading DOM attrs for each log entry
- starts on "WidgetsReady" for Firefox consistency on page refresh (bootstrap not applied on 'load' after F5. so FF generates second `<button>`)
widget works on driver-names and is indifferent to upper\lowercases from the API
thanks!

UPD
- added changes for https://github.com/opnsense/core/issues/4836 

bootstrap popover on Action icon hover with rule number and description (if any) display.
open ruleID-prefiltered Live View on Action icon click
ie11,chrome,FF tested )
thanks!

### CODE REVIEW

**Comment by kulikov-a** [comment]
@AdSchellevis Hi! sorry, I prepared for a pr for https://github.com/opnsense/core/issues/4836 (not so much code realy). may I combine changes from this pr with the new one. or should I make them separate and then resolve the conflict in one of them (if\when someone will be merged)?

**Comment by fichtner** [comment]
If it touches the same file I think it’s ok

**Comment by kulikov-a** [comment]
@fichtner yep. Thanks! preparing a combined pr with explanations

**Comment by kulikov-a** [comment]
seems to be ready for review. decided to add commits to this pr to make it easier to distinguish changes for different FRs on review

**Comment by AdSchellevis** [comment]
@kulikov-a looks really nice, personally I would prefer to keep the `<select id='filterlogentriesinterfaces' ..` as it was to prevent cluttering php and javascript, but I'll let it go this time since technically it's not wrong. I did wrap and improve your parameter parsing in the live view a bit (https://github.com/opnsense/core/commit/352d5de372cb0805ad631de67b0a238324472134), so we can easily reuse this later to store selections (in localstorage?), I think that was also a ticket somewhere which probably makes sense and shouldn't be to hard to add.

Thanks a lot for  your efforts!

**Comment by kulikov-a** [comment]
@AdSchellevis Wow thanks!!
yes, my parsing was very primitive. thanks for making it really useful )

**Comment by AdSchellevis** [comment]
@kulikov-a if you're looking for a new challenge, you could try to add a "save local selection" option, so you can easily switch between presets (https://github.com/opnsense/core/issues/4859). No pressure, only if you have the spirit for it.

**Comment by fichtner** [comment]
Very nice, thank you @kulikov-a

**Comment by kulikov-a** [comment]
@AdSchellevis @fichtner thanks!! :blush:
yes, it would be interesting to try to make stored filter templates though I'm afraid you will have a lot of work fixing my code)) and I might be a little slow until early May (moving the office. a lot of stupid time-consuming work starts). but if there is no strict deadline, I would love to.

**Comment by AdSchellevis** [comment]
@kulikov-a let's try it out and see how that goes, I've assigned you to the ticket, there's really no rush at all. Don't mind reviewing some of your code, it's quite decent and has lead to quite some nice improvements over the last months. Thanks!

**Pull request merged**
