### PR TITLE
fw categories: error if the category name is a number

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi
javascript throws an error if rule is in one category and category name is a number
Thanks!

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@kulikov-a nice catch! it seems that statically defined data tags are type casted automatically, so `data-category="X" ` doesn't match type with `data-category="1" ` .

**Comment by kulikov-a** [comment]
@AdSchellevis thanks!!
looks like a jquery featue (not sure if it's that good if the behavior cannot be changed inside the method): https://api.jquery.com/data/#data-html5

**Comment by kulikov-a** [comment]
@AdSchellevis hm. sorry, after reading jquery docs once again..now I doubt, maybe it would be quite correct to replace with `$(this).attr('data-category').split(',').forEach` once $ can repeat it with boolean?

**Comment by AdSchellevis** [comment]
@kulikov-a I think the toString() is safe enough to be honest

**Comment by kulikov-a** [comment]
of course it should still work. thanks again )

**Pull request merged**
