### PR TITLE
Ref #6596 - do not touch booting file

### PR DESCRIPTION
**Pull request by williamdes**
Ref: https://github.com/opnsense/core/issues/6596#issuecomment-1575160947

### CODE REVIEW

**Comment by fichtner** [comment]
sorry we don't do direct PR to stable branches. A cherry-pick -x from master is easier to carry out and trace back later.

**Comment by williamdes** [comment]
> What do you mean "contributing file"?

CONTRIBUTING.md

**Comment by fichtner** [comment]
About the master branch? First point says so for "Pull requests" but I don't mind making it more explicit.

**Comment by williamdes** [comment]
> About the master branch? First point says so for "Pull requests" but I don't mind making it more explicit.

I did open #6605 
Let's discuss on it about stable release updates and what I proposed :)

**Pull request closed without merging**
