### PR TITLE
Feature: add cert description to filename on download

### PR DESCRIPTION
**Pull request by tofuSCHNITZEL**
This PR aims to add enhance the cert download experience by adding the cert description to the filename. This is especially useful if you download multiple certs because then you can distinguish between them by their filename.

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@tofuSCHNITZEL https://github.com/opnsense/core/commit/e91e2fc2bb81a2b2c3dbbba8b78fc3519e3361d9 should do the trick

**Comment by tofuSCHNITZEL** [comment]
Hi,
thanks for the fast response... I think there are some issues with you changes in https://github.com/opnsense/core/commit/e91e2fc2bb81a2b2c3dbbba8b78fc3519e3361d9
please see my comments
https://github.com/opnsense/core/commit/e91e2fc2bb81a2b2c3dbbba8b78fc3519e3361d9#r147469705

**Comment by AdSchellevis** [comment]
@tofuSCHNITZEL thanks, force pushed an update in https://github.com/opnsense/core/commit/58dee6f789ae0f0b0c75e84ca3f9a240604d5b71

**Comment by tofuSCHNITZEL** [comment]
Thanks.
sorry, just out of curiosity... Why not request changes to my PR and then merge it?

**Comment by AdSchellevis** [comment]
you're welcome, often we do comment and merge, but documenting requested changes takes time as well in which case offering the proposed version is sometimes just less time consuming.

**Pull request closed without merging**
