### PR TITLE
Config::save : call microtime(true) once

### PR DESCRIPTION
**Pull request by csbyte**
Fixes https://github.com/opnsense/plugins/issues/2958

### CODE REVIEW

**Comment by fichtner** [comment]
@csbyte your patch is outdated, please rebase properly on master and try to adhere to PSR-12 style requirements.

**Comment by csbyte** [comment]
What do you mean, outdated? It is based on latest master already.

**Comment by fichtner** [comment]
Sorry, not true.

**Comment by AdSchellevis** [comment]
@csbyte thanks!

**Pull request merged**
