### PR TITLE
Update authgui.inc

### PR DESCRIPTION
**Pull request by cbasolutions**
Added autocapitalize="off" autocorrect="off" to the input for the logon form usernamefld. When using from an iPhone/iPad the first character of the username is capitalized automatically.

### CODE REVIEW

**Comment by fichtner** [comment]
Thanks, works. :) Since this is your first pull request: do you agree to license this and all other contributions under the 2-Clause BSD license?

**Comment by KarstensC** [comment]
Good morning Franco,

Off cause I do agree, because the 2-clause BSD License, in my 
understanding, is meant to make the world better: it gives real freedom 
(software context) and sets the pace: if you can't program a better 
version so why not just taking the good BSD-licensed software already in 
existence?

First I preferred a commons license for the opnsense-wiki, then I chose 
a FreeBSD document license - when I had learned more about the 
differences in the licenses.

And , hey, this is my first official contribution to a published 
(public) software -tadaa!

Cheers, C..

**Comment by fichtner** [comment]
@KarstensC I don't think this is your pull request? :) see: @cbasolutions

**Comment by KarstensC** [comment]
No, Franco, I do have only /KarstensC

I do not know how to change the master/stable/15.7 upstream address, If 
you could tell me would be nice, otherwise I have to goole it.

Everything I did is based on recipes from Github and the www.


/usr/home/uo/GIT/KarstensC/core
% git remote -v
origin	https://github.com/KarstensC/core.git (fetch)
origin	https://github.com/KarstensC/core.git (push)
upstream	https://github.com/opnsense/core.git (fetch)
upstream	https://github.com/opnsense/core.git (push)
%

"master" seems to be a working directory, or tmp, or dynamic repo, and 
15.7 seems to be the conservative directory with less changes, right?

**Comment by fichtner** [comment]
Christian, you are hi-jacking the wrong pull request :D Will reply in the correct one.

**Comment by cbasolutions** [comment]
I agree to the 2 clause license 

https://wiki.opnsense.org/index.php/OPNsense_license

bcj

**Pull request merged**
