### PR TITLE
Add missing entries to Dpinger advanced section

### PR DESCRIPTION
**Pull request by marjohn56**
It's only taken 8 months to do this.. impressive. :)

### CODE REVIEW

**Comment by marjohn56** [comment]
Typo correction

**Comment by fichtner** [comment]
Applied modified version. Thanks! data_payload is still unused. Do we need it?

**Comment by marjohn56** [comment]
Could not work out what that's supposed to be used for... I guess not until we do.

**Comment by fichtner** [comment]
Let‘s remove it then, -d 0 option seems to be the default anyway.

**Pull request closed without merging**
