### PR TITLE
vpn_openvpn_server.php: netbios options prettify

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi!
NetBIOS options in server config looks a bit ugly (especially in dark themes).
Can we add a couple of breaks to prettify it?
before:
ovpn_nb1

after:
ovpn_nb2

Thanks!

### CODE REVIEW

**Comment by AdSchellevis** [comment]
hmm, I think officially it should have been a label for the input tag, if I'm not mistaken these are formatted properly (have tried yet)

**Comment by kulikov-a** [comment]
in my opinion this is CSS: select's is display: inline-block; inputs is display: block;
so it doesn't look very good with current formatting (input and select in same div)

**Comment by AdSchellevis** [comment]
let's use your fix, the rest of the page handles these issues in similar matter and label has the same issue indeed. thanks!

**Comment by kulikov-a** [comment]
Thanks!
fast as always )

**Pull request merged**
