### PR TITLE
Update dhcpd.inc plugin for manage custom parameter.

### PR DESCRIPTION
**Pull request by agostinimarco**
Hi, I hope this is the right way to propose a pull request, sorry for my precedent malformed comunication :-)

I would propose to modify /usr/local/etc/inc/plugins.inc.d/dhcpd.inc to allow the include of an external file in /var/dhcpd/etc/dhcpd.conf that can be edited directly from the shell.

I have the necessity to add personalized parameter to isc-dhcp configuration file that is not managed by opnsense web interface.

I can't manually modify dhcpd.conf because the dhcpd plugin, normally, overwrite the dhcpd.conf file and than restart dhcp service every time something chance on configuration file or after a opnsense reboot.

With the code I proposed, I will add customized parameter to an external file without touch anithing else on the core or web interface.

### CODE REVIEW

**Comment by xeucs** [comment]
Hi,

will this feature be present in version 22.1?

Thank you

**Comment by fichtner** [comment]
@xeucs PR still open, no?

**Comment by xeucs** [comment]
@fichtner

when do you think this feature will be present?

Thank you

**Comment by fichtner** [comment]
I don’t know. 22.1 has required a large amount of work to get done in time.

**Comment by xeucs** [comment]
Hi,

do you have any updates on this feature? 

Thank you

**Comment by fichtner** [comment]
No.

**Comment by xeucs** [comment]
Hi,

When will this feature be available?

Thank you

**Comment by fichtner** [comment]
Likely 22.1.7.

**Comment by xeucs** [comment]
Hi,

when this feature will be available in the GUI?

Thank you

**Comment by fichtner** [comment]
It's not a GUI feature. Please read the documentation at https://docs.opnsense.org/manual/dhcp.html#advanced-settings

**Pull request closed without merging**
