### PR TITLE
Update rulecache.py

### PR DESCRIPTION
**Pull request by kulikov-a**
catch exception in rule metadata parsing

### CODE REVIEW

**Comment by AdSchellevis** [comment]
we're not going to catch and silence an exception like this, best open a ticket containing the test case that fails so we can add the proper condition in there. probably all it needs is one line like:
`
record['metadata'][parts[0]] = parts[1] if len(parts) > 1 else None
`

**Comment by kulikov-a** [comment]
ok. thank you. 
"record['metadata'][parts[0]] = parts[1] if len(parts) > 1 else None"
can set very long string in rule details metadata label. 
ticket: 
https://github.com/opnsense/plugins/issues/2005
will post bad formatted PTReasearch rule strings there
Thanks!

**Comment by AdSchellevis** [comment]
ok, better close the issue there, use our template for a bug report in core, I'll take a look.

**Comment by kulikov-a** [comment]
ok, thanks
https://github.com/opnsense/core/issues/4302
closing issue in plugins

**Pull request closed without merging**
