### PR TITLE
webgui: fix syntax error

### PR DESCRIPTION
**Pull request by Greelan**
My apologies - I had moved the include directive from a different line in a previous commit and did not update it for the next context. This revision has been tested to work. Sorry - sloppy work

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@Greelan can you rebase? I just merged the other one this morning

**Comment by Greelan** [comment]
Yeah, sorry, give me a bit to fix

**Comment by AdSchellevis** [comment]
no problem, take your time

**Comment by Greelan** [comment]
Closing to create new PR

**Pull request closed without merging**
