### PR TITLE
missing prototype.js in protochart directory

### PR DESCRIPTION
**Pull request by tomcheung789**
fix blank chart on the diag_logs_filter_summary page.

### CODE REVIEW

**Comment by fabianfrz** [comment]
Are you sure that Prototype does not conflict with jQuery?

**Comment by fichtner** [comment]
It's a sensible fix in general, but @fabianfrz is right: we don't want prototype back.

**Comment by AdSchellevis** [comment]
I will remove the include later today.. probably we forgot to remove this one.

**Comment by fichtner** [comment]
And how do we adapt the missing chart?

**Comment by AdSchellevis** [comment]
I thought to replace that with http://d3js.org/ which was an earlier idea of @fabianfrz for some other insights and if possible I would like to standardize on one graphics library (d3js is very powerful).

But replacing the current code costs me a bit more time than I figured, what if?
- we pull this in for now to make the current graphs work
- add an issue assigned to me, to replace the graph library for d3js
- kill prototype when the other issue is solved

**Comment by fichtner** [comment]
ok, if there is an issue in the bug tracker to remember this I'm in :)

**Comment by AdSchellevis** [comment]
Ok, I'm pulling this in then

**Comment by AdSchellevis** [comment]
For future reference, the issue which should remove this again:
https://github.com/opnsense/core/issues/294

**Comment by fabianfrz** [comment]
@AdSchellevis no the page I created did exactly the same but it used a sample code from d3 and I am not sure about the license if we can use it so it is still not used (also used a barchart instead)

**Comment by AdSchellevis** [comment]
@fabianfrz the license of d3js shouldn't be an issue it's a quite similar license as prototype.js. But the implementation side we have to do some work on I guess. Eventually we could also use d3 for dashboard widgets, like http://bl.ocks.org/tomerd/1499279 for example.

I just haven't had the time to dive into it yet.

**Comment by fabianfrz** [comment]
yes but the samples are gists which don't contain license information.

**Pull request merged**
