### PR TITLE
BUGFIX: Patch for https://github.com/opnsense/core/issues/4133

### PR DESCRIPTION
**Pull request by drivera73**
Proposed fix for Issue 4133 that detects the intended gateway address directly from the interface if it's not explicitly set via the environment.

### CODE REVIEW

**Comment by AdSchellevis** [comment]
It's probably a good idea to investigate if the desired address isn't set in any of the other env variables (maybe `ifconfig_pool_remote_ip` ?) Adding a lot of scripting here is quite prone to errors and vague issues, besides that we don't have a very good testbed to conclude this won't break existing setups.

https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/

> ifconfig_pool_remote_ip
> The remote virtual IP address for the TUN/TAP tunnel taken from an –ifconfig-push directive if specified, or otherwise from the ifconfig pool (controlled by the –ifconfig-pool config file directive). This option is set on the server prior to execution of the –client-connect and –client-disconnect scripts.
>

**Comment by fichtner** [comment]
And please don't mix fixes and style updates. It makes review practically impossible.

**Comment by drivera73** [comment]
> It's probably a good idea to investigate if the desired address isn't set in any of the other env variables (maybe ifconfig_pool_remote_ip ?) Adding a lot of scripting here is quite prone to errors and vague issues, besides that we don't have a very good testbed to conclude this won't break existing setups.

I did try to see if one of the parameters sent via _**--up**_ could fit the bill, or failing that if any of the environmental available at execution time for the script provided the correct value. Neither yielded any useful results.

For evidence:

* These are the parameters sent to the script:

`ovpnc6 1500 1558 172.94.108.209 255.255.255.192 init`

* This is the environment the script executes in (sorted, for easier reading):

```
PWD=/
X509_0_C=HK
X509_0_CN=Secure-Server
X509_0_L=HK
X509_0_O=Secure-Server
X509_0_OU=IT
X509_0_ST=Central
X509_0_emailAddress=mail@host.domain
X509_0_name=changeme
X509_1_C=HK
X509_1_CN=Secure-ServerCA
X509_1_L=HK
X509_1_O=Secure-ServerCA
X509_1_OU=IT
X509_1_ST=Central
X509_1_emailAddress=mail@host.domain
X509_1_name=Secure-ServerCA
common_name=Secure-Server
config=/var/etc/openvpn/client6.conf
daemon=1
daemon_log_redirect=0
daemon_pid=85651
daemon_start_time=1590586223
dev=ovpnc6
dev_type=tun
foreign_option_1=dhcp-option DNS 172.94.108.3
foreign_option_2=dhcp-option DNS 172.94.108.5
ifconfig_broadcast=172.94.108.255
ifconfig_local=172.94.108.209
ifconfig_netmask=255.255.255.192
link_mtu=1558
proto_1=udp4
remote_1=uswdc2-ovpn-udp.pointtoserver.com
remote_port_1=53
script_context=init
script_type=up
tls_digest_0=c4:21:55:de:da:b2:95:87:2f:16:66:a2:33:9b:fd:8d:95:31:a2:3a
tls_digest_1=1e:9e:f4:a4:a7:62:d9:20:78:ab:3f:aa:96:f1:88:02:f0:4b:e4:99
tls_digest_sha256_0=85:aa:36:26:78:4b:33:99:68:22:8a:dd:2a:0c:d8:a5:33:46:28:59:c0:2f:e3:07:cc:90:6a:85:1d:a6:1a:32
tls_digest_sha256_1=cf:db:d6:4f:77:bb:b7:c8:dc:80:41:19:b4:ee:3d:f3:71:a1:48:12:93:0c:ff:2c:73:68:81:bf:4f:e9:ac:4d
tls_id_0=C=HK, ST=Central, L=HK, O=Secure-Server, OU=IT, CN=Secure-Server, name=changeme, emailAddress=mail@host.domain
tls_id_1=C=HK, ST=Central, L=HK, O=Secure-ServerCA, OU=IT, CN=Secure-ServerCA, name=Secure-ServerCA, emailAddress=mail@host.domain
tls_serial_0=2
tls_serial_1=14472060699488478373
tls_serial_hex_0=02
tls_serial_hex_1=c8:d7:16:87:a8:e6:e4:a5
trusted_ip=172.94.108.4
trusted_port=53
tun_mtu=1500
untrusted_ip=172.94.108.4
untrusted_port=53
verb=4
xormask_1=
xormasklen_1=0
xormethod_1=0
```
Finally, the _**ifconfig**_ output for the device:
```
# ifconfig ovpnc6
ovpnc6: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1500
	options=80000<LINKSTATE>
	inet6 fe80::2e0:67ff:fe0e:3504%ovpnc6 prefixlen 64 scopeid 0xe 
	inet 172.94.108.209 --> 172.94.108.193 netmask 0xffffffc0 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: tun openvpn 
	Opened by PID 85651
```
I wholeheartedly agree that parsing user-facing **_ifconfig_** output is the least ideal way to find the correct value, however: what alternative is there? Is there a way to get the exact value we're looking for from ifconfig in some _machine-friendly_ syntax so we avoid mistakes?

As for breaking other setups, that did cross my mind. However: on tap modes (ethernet) there is no remote link address given to the interface, so the behavior of using the local IP as the gateway address remains.

I am, of course, open to any other solutions or suggestions.

Cheers!

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/0ad3ec432ff0d1ee45d9969424b7e5b19eb903e2 should probably fix the same issue

**Pull request closed without merging**
