### PR TITLE
Kea: Add direct reservation from leases page

### PR DESCRIPTION
**Pull request by pieewiee**
This PR adds the ability to create DHCP reservations directly from the leases page in Kea DHCP.

Ref: #8035

While this PR doesn't implement the full wizard functionality requested in the issue, it provides a first step towards that goal by allowing users to:
- Convert an existing lease to a reservation with a single click
- See which leases are already reserved
- Apply changes through an integrated Apply button

The current implementation automatically matches the subnet based on the IP address and transfers the existing hostname. This could be extended in the future to include a full wizard with more configuration options as suggested in the original issue.

Current features:
- Added addReservationAction to Leases4Controller
- Updated leases view with reservation button and Apply functionality
- Added proper validation and subnet matching for new reservations
- Visual indication of which leases are already reserved

This provides a foundation that could be expanded to include the full wizard functionality in the future.

Changes:
- Added addReservationAction to handle reservation creation
- Updated leases view with reservation button
- Added Apply button for service reconfiguration
- Added proper validation and subnet matching

lease

reserved

### CODE REVIEW

**Comment by pieewiee** [comment]
please give me your honest feedback - i would apricate your improvements!!!

**Comment by AdSchellevis** [comment]
I have to think about this, the feature overlaps with an earlier PR (https://github.com/opnsense/core/pull/8039), one of the main concerns I see is that it's generally not a good idea to assign addresses inside an existing pool as these are free for usage when the machine in question is not connected (at least with `isc-dhcp`). 

Ones we started to accept these in the legacy (isc-dhcp) server, we have had several reports about this behavior, which isn't ours to fix.

**Comment by pieewiee** [comment]
i could have checked other PRs before spending time on this. You maybe got another issue for me that i could support (something easy)?

honestly the other PR (https://github.com/opnsense/core/pull/8039) is better in terms of how he handled the add reservation

**Comment by AdSchellevis** [comment]
> i could have checked other PRs before spending time on this.

no problem, things happen.

> You maybe got another issue for me that i could support (something easy)?

Any particular topic in mind you would like to spend time on? There likely aren't a lot of easy ones, but I can search the list to see if something might be worth giving a try.

**Pull request closed without merging**
