### PR TITLE
First test commit to see if the local PC file /lang/de_DE.po

### PR DESCRIPTION
**Pull request by KarstensC**
would get into the GitHub fork repo and then into
the opnsense repo! Christian K.

### CODE REVIEW

**Comment by fichtner** [comment]
Christian, we do not merge into stable/15.7 via a pull request. All changes must be rebased on master and we'll make sure that important fixes will also go into stable/15.7 shortly before a release after an initial grace period to make sure the submissions are ok. If we accept both commits to stable and master at the same time it is a lot harder to merge patches. Please rebase your changes accordingly.

I don't know if you can revamp this pull request or if it needs to be closed. I'll leave it up to you.

Cheers,
Franco

**Comment by fichtner** [comment]
Too dangerous to leave open. I like to clickety-click on PRs. ;)

**Comment by KarstensC** [comment]
I have deleted the stable/15.7 clone on my pc and changed the settings in my KarstensC GitHub fork to master, sorry I though that would be the correct setting.
I'll try to merge with fabianfrz and then make a puill request again (I am reading docu ..)

**Comment by fichtner** [comment]
The master branch is up to date. Simply rebase against that. Normally, your commit should still be valid by doing the following on a clean branch:

    # git cherry-pick 95ab3c2

**Comment by KarstensC** [comment]
O.K. terminator "clicky" :)

**Pull request closed without merging**
