### PR TITLE
Improvements to Firewall Schedules

### LINKED ISSUE #6348: Schedule - Time Range Description Replaced with URL Encoded String
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

When saving a Time Range for a Schedule, the Time Range Description gets replaced with a URL encoded string.  For example, when I attempt to save the description as "9:00 PM to 11:59 PM", the string gets saved and replaced with "9%3A00%20PM%20to%2011%3A59%20PM", making the description very difficult to read. I'm new to OPNsense and first noticed this issue with 22.7.

**To Reproduce**

1. Go to **Firewall > Settings > Schedule** (https://[OPNsense IP]/firewall_schedule.php)
2. Click on the **Add** button (or edit an existing entry)
3. Configure the time range 
4. In **Time Range Description**, enter a description containing characters like spaces, colons, etc.
5. Click the **Add Time** button
6. The new entry will appear on the **Configured Ranges** row with the **Time Range Description** re-saved as a URL encoded string
7. Click the **Save** button
8. The new schedule will appear on the list of schedule entries, along with the **Time Range Description** as a URL encoded string

**Expected behavior**

The **Time Range Description** should appear just as I entered it. If a URL encoded string needs to be saved on the backend, that's fine. But when rendering the description, it must be URL decoded to not only make the description more readable, but also to prevent double-encoding in case the description were to be re-saved.

**Describe alternatives you considered**

I have no known workarounds or alternatives.

**Screenshots**

image
image

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

OPNsense 23.1.1_2 (amd64, OpenSSL)
Protectli VP2410
Intel® Celeron® J4125 2.0GHz Quad Core

### LINKED ISSUE #6349: Schedule - Start Time Not Resetting After Adding Time Range
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

After adding a time range to a schedule, the dropdown fields for both the **Start Time** and **Stop Time** do not reset back to the default values. This makes it cumbersome and confusing knowing when I have the correct time selected before clicking the **Add Time** button.

**To Reproduce**

1. Go to **Firewall > Settings > Schedule** (https://[OPNsense IP]/firewall_schedule.php)
2. Click on the Add button (or edit an existing entry)
3. Select the days and configure the time range to something different than the default values (i.e. set **Start Time** to **21:15** and **Stop Time** to **22:30**)
4. Enter a description like **test1** to help identify the time range after adding it
5. Click the **Add Time** button
6. Confirm that **test1** saved with the correct start and stop times
7. Select the days and configure the time range again to something from midnight to 11:59 PM (i.e. set **Start Time** to **00:00** and **Stop Time** to **23:59**)
8. Notice that the selections for the dropdowns won't change
9. Enter a description like **test2** to help identify the time range after adding it
10. Click the **Add Time** button
11. Confirm that **test2** shows the values you did select, but that they don't match the dropdowns

**Expected behavior**

Both the **Start Time** and the **Stop Time** dropdown select inputs need to reset after clicking the **Add Time** button and must also change whenever additional time ranges need to be added thereafter.

**Describe alternatives you considered**

The two workarounds that I came up with were to:

* Click the **Save** button after adding a time range, then going back in by editing the schedule, OR
* When making a selection for the **Start Time** or **Stop Time**, I have to select a different value than what's currently selected, then select the intended value.

**Screenshots**

**Before clicking the Add Time button**
image

**After clicking the Add Time button**
image

**0 is already selected when attempting to change the Start Hours**
image

**After clicking 0 for the Start Hours; 21 is still showing as the selected value**
image

**00 is already selected when attempting to change the Start Minutes**
image

**After clicking 00 for the Start Minutes; 15 is still showing as the selected value**
image

**After clicking the Add Time button; values don't match for second test**
image

**Relevant log files**

N/A

**Additional context**

N/A

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.1.1_2 (amd64, OpenSSL)
Protectli VP2410
Intel® Celeron® J4125 2.0GHz Quad Core

### PR DESCRIPTION
**Pull request by kuya1284**
- Fixes #6348 
- Fixes #6349 
- Implements some suggestions made in #4449
- Adds ability to disable a schedule
- Adds ability to set a start and end date for a schedule
- Simplifies and improves the concept of a repeating schedule on a weekly or monthly basis
- Adds more details to the Schedules list view 
- Miscellaneous code improvements
- Miscellaneous UX/UI improvements

### CODE REVIEW

**Comment by kuya1284** [comment]
Here are some screenshots to showcase the improvements/fixes:

image

image

image

image

image

**Comment by AdSchellevis** [comment]
@kuya1284 at a first glance I'm afraid we can't merge this, the aim should be to limit the codebase (cleanup and make it smaller) and trying to keep the data format as is. The problem is that we eventually need to migrate this to mvc as well, in which case a cleanups help, but adding more code and possible migration needs complicate future steps a lot.

**Comment by kuya1284** [comment]
@AdSchellevis sorry, I was hoping that with the improvements and the refactoring that it would help with making things easier with migrating to MVC. Is there anything I can do to help with the migration.

In terms of the data format, are you referring to the config property names? Would it help if I were to revert those? I was also trying to make things easier to manage and work with, and add support for new features. I was just trying to take the initiative to help since I know the rest of the team have higher priority bugs/features to work on and since there were plans to overhaul the Schedules anyway.

Anyway, please let me know what I can do to help get this merged in... if possible. Thanks.

**Comment by AdSchellevis** [comment]
@kuya1284 no problem, I know how it goes, seeing room for improvements and keep coding while there :) If the configuration data remains the same, it is less problematic, although I would prefer less code and trying to seek the bare minimum of what this needs so it's easier to migrate later.

About the configuration change, I was triggered by https://github.com/opnsense/core/blob/f916dadc57f79e10ff95504c74d90300f7dd69a4/src/etc/inc/filter.inc#L682 

Smaller steps might be easier to manage, keeping the changes focuses to `firewall_schedule.php` and `firewall_schedule_edit.php` alone certainly helps. 

When at some point moving to our MVC framework, quite some magic on this page isn't really possible and/or desired, in which case it helps if there's less to read while thinking about a way to either migrate or help people move.

**Comment by kuya1284** [comment]
@AdSchellevis How would you propose adding the ability to disable a schedule, as well as adding a start/stop time to the schedule by limiting the changes to just those two files? I could've actually refactored the code to leverage Phalcon, but I felt that would've been an even bigger change that would've gone beyond the scope of the initial phase of making improvements. I was considering this just the first phase before moving the code base to leveraging the framework. I even wrote classes in those two files to help (hopefully simplify) the transition.

As far as the configuration changes go, I'm sorry you were triggered by that change. The `filter_get_time_based_rule_status()` function needed refactoring for two reasons:

* It contained logic that needed to be simplified
* New logic was needed to add support for the new config properties for enabling/disabling a schedule, as well as for the start and stop times

The reason for changing the names is to add clarity to each config property:

* Pluralizing property names to make it clear that it may hold more than 1 value
* Renaming `position` to make it clear that it represents the day of the week
* etc.

I even wrote the code such that nothing should break since the old config properties would still be referenced (and eventually get renamed to the new names).

Per your comment here: https://github.com/opnsense/core/issues/6348#issuecomment-1441445504, and in other threads where I've read other devs asking for community help, I was merely making an attempt to help the OPNsense team and community by contributing my personal (sleep) time to improve just the Firewall Schedules. I get that it's a relatively big change, but thank goodness I didn't make one giant monolithic commit and smaller commits. I also get that things will need to be refactored once again when transitioning to the framework. Nonetheless, you gotta start somewhere. Sometimes it takes baby steps, and other times it takes hops to get there. This change was by no means intended to be a leap forward.

It's your call if you want to accept the change. Like I said, I was just trying to help, but it would be sad if this were all for naught since a lot of people could benefit from it.

**Comment by AdSchellevis** [comment]
@kuya1284 I certainly understand that you spend quite some time on this, the problem is that in order to merge it, we also need to invest quite some time in terms of review and possible cleanups. 

For core commits we tend to be strict as people will be looking at us when it comes to regressions, which in our experience has the tendency of consuming quite some resources on our end. 

Sometimes the problem is that reviewing can take more time than building the feature on our end. As the original file more than doubled in lines of code, the effort to process it grew substantially. In our previous experiences of cleaning up legacy code, the result in lines of code was lower than what we started with.

I'll leave the PR open for now, but I'm afraid it's not going to make the bar at the moment.

**Comment by kuya1284** [comment]
@AdSchellevis I'm completely understand. Well, thanks for taking the time to do a quick review. I know dealing with regressions can be a PIA. It would be nice to have some unit tests to test the changes, but I didn't see anything like that available. But I know that there's more to it than just unit testing.

If you ever have a chance, and if you haven't already, please give the changes a try in a branch or something. I'm sure you'd be happy at the very least with the functionality and UX. 

If you do need help with this in the future, please don't hesitate to ping me. Thanks.

**Comment by kuya1284** [comment]
@AdSchellevis oh, and by the way, I'll cherry-pick the fixes for those bugs and submit separate PRs for those so at least those issues will be fixed. I'll be sure to keep the changes to the bare minimum just to get them fixed.

**Comment by AdSchellevis** [comment]
@kuya1284 thanks, smaller bugfixes are easier to merge indeed.

**Comment by AdSchellevis** [comment]
I think we can close this, we fixed some of this in other PR's

**Pull request closed without merging**
