### PR TITLE
sticky sub-submenu

### PR DESCRIPTION
**Pull request by opnsenseuser**
sticky sub-submenu on mouseout when next item does not have a sub-submenu
-> https://github.com/opnsense/core/issues/2554

### CODE REVIEW

**Comment by opnsenseuser** [comment]
@franco sticky sub-submenu fix

**Comment by fichtner** [comment]
Great, thank you! Merged manually changing tabs to spaces.

**Comment by opnsenseuser** [comment]
@fichtner sorry for the tabs... !! :-(

**Comment by fichtner** [comment]
all good, no worries at all :)

**Pull request closed without merging**
