### PR TITLE
ARP Table: hostname uses reverse DNS lookup as fallback

### PR DESCRIPTION
**Pull request by soif**
Arp table only relies on dhcp-leases entries to get the hostname. So when using an external DHCP server, or for IP addresses that are not assigned by DHCP, the displayed hostnames are always blank.

Features added:
- if hostame is not found in the dhcp-leases, the hostname is fetched from a DNS PTR query, (using the system's DNS server).
- use_dns variable can allow/disallow this behaviour (useful is someone would like to move this to a system preference)

HTH

### CODE REVIEW

**Comment by AdSchellevis** [comment]
A similar construction as used for the routes might be acceptable, putting the burden to resolve (with timeouts for everyone) isn't, so if you're up for it, please change the PR to include the option to the endpoint, either as uri part or as parameter (latter might make more sense at the moment).

For some inspiration, the following code blocks are being used in the route dialog.

https://github.com/opnsense/core/blob/745d46c4eeefb33566f5fe25024d6235846660fd/src/opnsense/mvc/app/views/OPNsense/Diagnostics/routes.volt#L62

https://github.com/opnsense/core/blob/745d46c4eeefb33566f5fe25024d6235846660fd/src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/InterfaceController.php#L137-L142

https://github.com/opnsense/core/blob/745d46c4eeefb33566f5fe25024d6235846660fd/src/opnsense/scripts/routes/show_routes.py#L42

ps:  removing the `-n` from arp would resolve in the same pass.

**Comment by soif** [comment]
Hi thanks for the fast review!

You're perfectly right. I wrongly assumed that the ARP table should typically be only filled with LAN IP addresses where DNS timeout is usually not an issue for in-addr.arpa zones. But for cases where OPNsense is used mainly with  publically routables ip addresses, that obviously would create timeout issues.

**Thanks** for the inspiration examples (helps a LOT):  I'm gonna fix the PR to make DNS resolving optionnal, like in routes.

**Comment by soif** [comment]
Here it is. 

Notice that:

* i used the -r as additional parameter, that triggers the Reverse DNS. 
Without -r the commands behaves exactly as in the latest release. 

* I've added a natural sort of IP addresses (separate commit, to be easily reverted), as requested in #4185.
This is visible when using the command line:
`configctl "interface list arp -r"`
When using the GUI, and because Javascript sort the results, it might still be usefull, when for example sorting by Interface or Interface name.

HTH

**Comment by AdSchellevis** [comment]
@soif thanks, I've made some small cleanups in https://github.com/opnsense/core/commit/1548ae0eb79bde1f059f58c0a61658b5e33a0c9f before merging. The natural sort has been left out for now as it will likely lead to new tickets since it doesn't fix the complete issue.

**Pull request merged**
