### PR TITLE
Add PPTP to ignore for IPfw

### PR DESCRIPTION
**Pull request by iMiMx**
https://github.com/opnsense/core/issues/1907

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@iMiMx sorry, I was reading through my email from oldest to newest, missed your pull. thanks anyway

**Comment by fichtner** [comment]
l2tp != pptp

**Comment by fichtner** [comment]
sorry, now I missed the second commit :D

**Comment by iMiMx** [comment]
Was scratching my head a little ;)

**Comment by fichtner** [comment]
To be fair, the first commit message said pptp but fixed l2tp so that’s where I missed the second one that actually fixed it. :D

Thank you for the report!

**Pull request closed without merging**
