### PR TITLE
Locale.en.canonical xcatch upstream

### PR DESCRIPTION
**Pull request by dotike**
Adding a few lines to ensure the .pot file isn't so confusing/daunting.

Ostensibly, language translators will start by precisely copying this file- so a bit of OPNsense is good in the header IMHO.

### CODE REVIEW

**Comment by fichtner** [comment]
I found a bit of nastiness using your C-format pot file diffed against the PHP-format file generated by the Makefile: https://github.com/opnsense/core/commit/321d458ea07d86417ca0dbc2176ca231ee4b089d

Gonna clean those up before merging this :)

**Comment by dotike** [comment]
Yikes!  Franco: Just nuke the .pot file and generate one using 'make translate'.

Start it from scratch now while there's a clean chance at it!

**Comment by fichtner** [comment]
Hmm, I don't like using git versioning info from there, git might not be installed.
The file is already in version control once checked in, if we use -F the diff is easily readable/mergabe && when we wrap up a package the file will be generated as *.mo anyway. We don't even have to ship the po/pot files in the package.

**Comment by dotike** [comment]
Understood- I'll pull it out now.

I guess the fact that xgettext seems to get the date in there is more than sufficient for translators watching to see how the file tracks the source.

**Comment by dotike** [comment]
Closing- too much for too little.

**Comment by fichtner** [comment]
ACK, will regenerate once more after the current fixing session, pushing -L PHP back (seems to remove some C-format duplication too). I'll let you know. :)

**Comment by dotike** [comment]
10-4 I'll leave the ball in your court from here, and go bootstrap JP...

/salute

**Pull request closed without merging**
