### PR TITLE
Added logging toggle for firewall rules

### PR DESCRIPTION
**Pull request by johnaheadley**
This is a proposed solution for:

Feature request: Option to enable logging for all firewall rules at once #3124

I propose this as a superior solution to a single button that enables logging on all policies at once.

Having a logging toggle on each firewall rule allows a nice overview of what policies have logging enabled and which don't, as well as giving the admin the ability to quickly enable logging for all policies that don't currently have it enabled.

### CODE REVIEW

**Comment by AdSchellevis** [comment]
Hi @johnaheadley,

Thank you for your PR, I have some remarks about the proposed changes.

In stead of using a new icon, I would suggest keeping the original info icon, the info icon is more explicit about the feature that's enabled. 
image
Maybe something like:
image

Looking at https://github.com/opnsense/core/issues/3124, I would expect there's some kind of "enable/disable" selected button as well. Question is how this should look, currently you can enable/disable from the buttons down right, but it's already quite full there:

image

Best regards,

Ad

**Comment by johnaheadley** [comment]
Hey @AdSchellevis,

Thanks for the feedback. The tricky part about keeping the old icon is how to handle differentiating between logging on/off when the rule is disabled. Here are two options I came up with:

Option 1:

Option1

Option 2:

Option2

Option 1 has the downside that the icon does not go text-muted when logging is enabled but rule is disabled.

Also, I can move the logging icon to the be the last icon displayed, like in your photo, if that is what you think looks best.

As far as the enable/disable logging on selected rules option, I agree that it is crowded in the bottom right, but I can't think of a better way to handle that. Here is what it could look like if we were to implement the icons in Option 2.

LogSelected

Once we work through the design choices then I can submit a new commit with the changes.

**Comment by AdSchellevis** [comment]
@johnaheadley I would like to vote for option 1, when disabled, the state of logging is not very relevant anyway. The location of the item (last item, next to action) is less problematic, personally I can live with both and don't have a preference.

**Comment by johnaheadley** [comment]
Alright, so the icons are now back to the fa-info-circle, and the coloring is consistent with the first match icon - regardless of the enable/disable status of the rule, the icon is text-info if logging is enabled or text-muted if not.

Screen Shot 2019-08-04 at 10 49 04 AM

This gets carried over to the newly added icons for the enable/disable logging on selected rules.

Screen Shot 2019-08-04 at 10 13 07 AM

Finally, this is consistent in the legend, where I tried to make the text reflect that the rule status doesn't affect the icon color.

Screen Shot 2019-08-04 at 10 13 59 AM

(Also, sorry for the bit of a mess with the commits. I am still learning git.)

**Comment by fichtner** [comment]
FWIW, the log enable/disable for selected seems displaced.... we can't add buttons for all features here and the only one that is important enough is enable / disable the rule itself

**Comment by johnaheadley** [comment]
Should I remove the enable/disable log for selected buttons and we just leave the toggle on the individual rules to satisfy the feature request?

Otherwise, we can move the buttons somewhere else in the footer bar so that it doesn't wrap around in the last column?

For example, bottom left

Screen Shot 2019-08-04 at 11 59 00 AM

**Comment by fichtner** [comment]
I would opt for removal. While it's nice to enable all you will kill your "normal" logging state and you don't have immediate feedback from here anyway. It would be much cooler if we had a "overlay" live log feature where we can toggle away from the configuration to see what happens and disable logging selectively or collectively so you can "drill down" on your logging. But that's a much larger goal for later perhaps.

**Comment by AdSchellevis** [comment]
Thinking about this, the main issue in the log toggle is the page reload, what if we toggle the icon state async and keep the page as is? I would be more user friendly, and the amount of work toggling a set of rules would be close to the same.

@johnaheadley sorry about the noise, I know I asked about the "toggle selected" thing, in retrospective I agree with @fichtner on this point. 

I can fix the Javascript code for the single toggle action, just let me know if you agree.

**Comment by fichtner** [comment]
I love the "responsive" approach for the toggle. Nice idea.

**Comment by johnaheadley** [comment]
Hey @AdSchellevis, no worries. I agree, please feel free to make any changes you like.

**Comment by AdSchellevis** [comment]
@johnaheadley there you go https://github.com/opnsense/core/commit/c8b57d0bfecd1e654507007b2c39c4a4c1eacacb, thanks for your contribution!

**Comment by johnaheadley** [comment]
@AdSchellevis, you're welcome! Also, I'm testing out the async toggle you added - it is a great user experience, but I see a small issue:

If I enable/disable the log status and/or the rule and then refresh the page, I get the message to "Apply changes". Was your goal to have these two actions not require a "Apply changes" button press?

**Comment by AdSchellevis** [comment]
@johnaheadley hmm, it needs a reload to be effective, so we should probably show some button. Only small issue is that it will scroll your page down when showing the normal button.

**Comment by AdSchellevis** [comment]
@johnaheadley can you try https://github.com/opnsense/core/commit/d2fc3c2567cf0959407b7d1da409110e3784aa46?

**Comment by johnaheadley** [comment]
@AdSchellevis d2fc3c2 looks good!

**Pull request merged**
