### PR TITLE
Replace radvd with rtadvd - Clean

### PR DESCRIPTION
**Pull request by marjohn56**
Clean version applied against Master source 14-11-2020
Something went amiss with my repo for #4432 which left me unable to merge cleanly, so this PR replaces it..

### CODE REVIEW

**Comment by MartB** [comment]
So far this has been stable for me, can someone from opnsense check this out?

**Comment by MartB** [comment]
So far this has been stable for me, can someone from opnsense check this out?
@fichtner what do you think about this?

**Comment by fichtner** [comment]
@MartB there is not enough data to indicate rtadvd is the better choice so far. We have some users with a multitude of problems which could range from software to equipment to ISP and some might try rtadvd and say it works, some will not reply because it doesn't and nobody who uses radvd year in year out with no issues is going to try rtadvd. Making a decision here now is impossible.

**Comment by marjohn56** [comment]
I'll maintain and enhance this patch as long as it's needed, But that means users must test out RADVD when updates/changes that could resolve the perceived  radvd issues are made.

**Comment by s1shed** [comment]
> I'll maintain and enhance this patch as long as it's needed, 

Thank you :)

> But that means users must test out RADVD when updates/changes that could resolve the perceived radvd issues are made.

Every time there's a new opnsense update I revert this patch to go back to radvd. So far I've have to go back to rtadvd each time for router advertisements to work. :|

**Pull request closed without merging**
