### PR TITLE
jQuery 3 migration - some progress

### PR DESCRIPTION
**Pull request by fabianfrz**
use the jQuery 3 syntax (for many cases - this is not complete).
* In most cases the function name must be moved into a trigger, on or off call.
* Libraries are not (yet) compatible (for example tokenize, bootstrap select)
* Plugins need migration as well

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@fabianfrz I can't find a reference of `click()` (https://api.jquery.com/click/) being deprecated, same seems to be the case for `focus()` and `unbind()`, can you explain these changes?

To be honest, I personally like the shortcuts better, but maybe there's some design document I missed somewhere, we have been running JQuery 3 + JQuery migrate for quite some time now, and I haven't seen any deprecation messages there either.

**Comment by fabianfrz** [comment]
@AdSchellevis the warnings are only shown if you don't use the .min.js variant. See:
https://github.com/jquery/jquery-migrate#development-vs-production-versions

And here is a reference:
https://github.com/jquery/jquery-migrate/blob/bf48bce49625e0c558c2f07dd514f2dfa5665334/warnings.md#jqmigrate-jqueryfnclick-event-shorthand-is-deprecated

**Comment by AdSchellevis** [comment]
@fabianfrz thanks for explaining, I just find it odd that there seems to be no reference of these deprecations in the jQuery api docs.

We should might consider ditching jquery-migrate as well at some point, as it seems to be of minimal use at the moment.

**Comment by fabianfrz** [comment]
@AdSchellevis we cannot. Some libraries won't work with it anymore.
See this screenshot for examples:

grafik

**Comment by AdSchellevis** [comment]
@fabianfrz are you sure? the click() events seem to be working fine without the jquery-migrate import on my end.

**Comment by fabianfrz** [comment]
@AdSchellevis yes but due to the deprecation I want to get rid of it - it is currently defined in the jQuery source: https://github.com/jquery/jquery/blob/master/src/event/alias.js#L10

There must be a reason why this message is printed and the warning is thrown.

**Comment by AdSchellevis** [comment]
@fabianfrz to be honest, most libs just seem to be using these binds (including the latest bootstrap-select, which was requested here https://github.com/opnsense/core/issues/2848) and the docs from jQuery aren't in sync with their desired behaviour. I kind of expect it's unlikely this will go away soon.

Maybe it's better to wait until there is a version out there that doesn't support it and see other libraries pick this up as well. I don't want to be in the situation that we need to upstream these kind of patches to the rest of the world.

Your intentions are good, don't get me wrong, but I'm unsure we should try to fix this...

**Comment by fabianfrz** [comment]
@AdSchellevis I've looked into it - the short syntax should have been deprecated with 3.3 but it looks like it has ben forgotten. I have created a ticket for clarification in the jQuery project - you can see the issue above this comment.

**Comment by AdSchellevis** [comment]
@fabianfrz thanks, let's wait for the jQuery people then.

**Comment by L1ghtn1ng** [comment]
@fabianfrz Just an FYI this branch has a conflict with src/opnsense/www/js/opnsense_theme.js

**Comment by AdSchellevis** [comment]
3.4.1 had some shorthands deprecated (https://github.com/opnsense/core/commit/ac970161058b1d7944284434bce909c0bb48fbdb), we better fix this when needed, a lot of code depends on the ones we use now (including some of our dependancies)

**Pull request closed without merging**
