### PR TITLE
feat: add ipxe configuration to dhcp netboot options

### PR DESCRIPTION
**Pull request by onedr0p**
This PR adds the ability to set a iPXE address for netbooting, which previously is only possible to do by editing the files directly.  I added a new field `ipxeaddress` that when set will ignore all the `filename*` fields and allow people to boot off an iPXE address.

There is definitely a few different ways of tackling this issue, so please let me know if you want it done another way. I chose the most logical method to me.

Fixes: https://github.com/opnsense/core/issues/5162 
Related: https://github.com/opnsense/core/issues/3557

Thanks!

Signed-off-by: Devin Buhl <devin@buhl.casa>

### CODE REVIEW

**Comment by fichtner** [comment]
@onedr0p sorry I had to trash the code you were trying to edit due to new arm additions not being rendered in all cases... can you rebase your PR?

**Comment by onedr0p** [comment]
@fichtner please ignore my silly commits, but I have updated the PR.

**Comment by fichtner** [comment]
@onedr0p no worries, thanks so far. We probably want the conditional in the loop that builds the conditional to avoid the disabling of filename handling... sort of how I tried to fix it previously. I will look into this next week when I'm back in the office.

**Comment by onedr0p** [comment]
@fichtner any update? Would be neat to see this in the upcoming 22.1 release :)

**Comment by alex-s-team** [comment]
hi, i found this pr too late and had already my own ipxe patch in place. i suggest only adding a variable named "filenameipxe" which if not empty loads the ipxe file (usually a script)

patch looks like this:

```

diff --git a/src/etc/inc/plugins.inc.d/dhcpd.inc b/src/etc/inc/plugins.inc.d/dhcpd.inc
index 55d8a8b64..1ef000100 100644
--- a/src/etc/inc/plugins.inc.d/dhcpd.inc
+++ b/src/etc/inc/plugins.inc.d/dhcpd.inc
@@ -1086,6 +1086,13 @@ EOD;
                 '00:0b' => 'filename64arm',
             ];
 
+            if (!empty($dhcpifconf['filenameipxe'])) {
+              $dhcpdconf .= "  if exists user-class and option user-class = \"iPXE\" {\n";
+              $dhcpdconf .= "    filename \"{$dhcpifconf['filenameipxe']}\";\n";
+              $dhcpdconf .= "  }";
+              $conditional = true;
+            }
+
             foreach ($filemap as $arch => $file) {
                 if (empty($dhcpifconf[$file])) {
                     continue;
diff --git a/src/www/services_dhcp.php b/src/www/services_dhcp.php
index 21c7403a7..bc74d8c7c 100644
--- a/src/www/services_dhcp.php
+++ b/src/www/services_dhcp.php
@@ -58,7 +58,7 @@ $config_copy_fieldsnames = array('enable', 'staticarp', 'failover_peerip', 'fail
   'defaultleasetime', 'maxleasetime', 'gateway', 'domain', 'domainsearchlist', 'denyunknown','ignoreuids', 'ddnsdomain',
   'ddnsdomainprimary', 'ddnsdomainkeyname', 'ddnsdomainkey', 'ddnsdomainalgorithm', 'ddnsupdate', 'mac_allow',
   'mac_deny', 'tftp', 'bootfilename', 'ldap', 'netboot', 'nextserver', 'filename', 'filename32', 'filename64',
-  'filename32arm', 'filename64arm', 'rootpath', 'netmask', 'numberoptions', 'interface_mtu', 'wpad', 'omapi', 'omapiport',
+  'filename32arm', 'filename64arm', 'filenameipxe', 'rootpath', 'netmask', 'numberoptions', 'interface_mtu', 'wpad', 'omapi', 'omapiport',
   'omapialgorithm', 'omapikey', 'minsecs');
 
 if ($_SERVER['REQUEST_METHOD'] === 'GET') {
@@ -988,6 +988,8 @@ include("head.inc");
                           <input name="filename32arm" type="text" id="filename32arm" value="<?=$pconfig['filename32arm'];?>" /><br />
                           <?=gettext('Set ARM UEFI (64-bit) filename');?>
                           <input name="filename64arm" type="text" id="filename64arm" value="<?=$pconfig['filename64arm'];?>" /><br />
+                          <?=gettext('Set iPXE boot filename');?>
+                          <input name="filenameipxe" type="text" id="filenameipxe" value="<?=$pconfig['filenameipxe'];?>" /><br />
                           <?= gettext('You need both a filename and a boot server configured for this to work.') ?><br/>
                           <br/><br/>
                           <?=gettext('Set root-path string');?>

```

as it is the same topic i didn't create my own pr, use the code if you like.

cheers

**Comment by fichtner** [comment]
@alex-s-team thanks a lot! this is nicer indeed and should work for @onedr0p as well

**Comment by alex-s-team** [comment]
you're welcome. thanks for the great work.

**Comment by razamatan** [comment]
just to be clear.  this does not fix #5162.  my particular use case needs the "else" clause to load undionly.kpxe to have non-iPXE clients to reload themselves with iPXE.   https://github.com/opnsense/core/commit/44858952740e4c668fb9ff0b0bbb037b13fba7d3 actually will support #5162's use case best.

**Pull request closed without merging**
