### PR TITLE
src: remove noodp and noydir, they do not serve any SEO purpose now

### PR DESCRIPTION
**Pull request by williamdes**
Ref: https://searchfacts.com/noodp-noydir-meta-tags/

I did learn this right now, and found all occurrences to remove them as the projects are long gone

### CODE REVIEW

**Comment by AdSchellevis** [comment]
The whole meta tag section might be rather useless for a firewall, I'll leave this one for @fichtner to assess.

**Comment by williamdes** [comment]
> The whole meta tag section might be rather useless for a firewall, I'll leave this one for @fichtner to assess.

IMO it's not because it could be quite easily exposed to internet, so to search engines and end up on Google for people to find instances to bruteforce in an even easier way

right ?

**Comment by williamdes** [comment]
Do I have something to change for this one @fichtner ?

**Comment by fichtner** [comment]
LGTM, thanks!

**Pull request merged**
