### PR TITLE
Update main.xml

### PR DESCRIPTION
**Pull request by Strykar**
Add CSV capability information to 'SSL no bump sites' form tool tip

### CODE REVIEW

**Comment by AdSchellevis** [comment]
I don't know if this is the place to add this, all tokenize inputs support the same in OPNsense. Maybe we better put this in the docs (for example here https://docs.opnsense.org/manual/gui.html)

**Comment by Strykar** [comment]
I saw the same tool tip in other places and assumed it was okay. Perhaps it is better in the docs, not my call.

**Comment by fichtner** [comment]
This can't really hurt, although I don't suggest updating the help entry of every single CSV-capable field as this would remove a lot of good translations for little benefit.

Slightly modified version committed as https://github.com/opnsense/core/commit/e6f5a191901063e64c6a22fd3a45528127808b65

**Comment by fichtner** [comment]
And thanks @Strykar :)

**Pull request closed without merging**
