### PR TITLE
Logs: add backward compatibility

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi.
For logs part of https://github.com/opnsense/plugins/issues/2776 and may close https://github.com/opnsense/plugins/issues/2786

set initial `severity` val to `None `and just add lines with missing severity (not set by parser or not in log) to the output. no fake prio - just empty field

Thanks!

### CODE REVIEW

**Comment by AdSchellevis** [comment]
I think we can just change the default facility as suggested, looking at the code, it doesn't look like 3 is converted anywhere else.

**Comment by kulikov-a** [comment]
@AdSchellevis sorry. tested little more (with proxy, dnscrypt etc). updated. how about that? )

**Comment by AdSchellevis** [comment]
@kulikov-a works for me, no level is indeed better than a random one. merge this one? or do you want to play with it more?

**Comment by kulikov-a** [comment]
@AdSchellevis i think im done) thanks!)

**Comment by AdSchellevis** [comment]
@kulikov-a thanks!

**Comment by kulikov-a** [comment]
Thanks!!

**Pull request merged**
