### PR TITLE
Add plugins_reconfigure to squid

### PR DESCRIPTION
**Pull request by kekek2**
If we reconfigure squid, we may need to reconfigure all plugins. Or reconfiguration of one plugin may require reconfiguration of other plugin.

### CODE REVIEW

**Comment by fichtner** [comment]
I'm pretty sure you can use plugins_configure() for this use case already, adding your own reconfigure points like "vendorproxyplugin" in your plugins, then just calling that. We just need to see how much core patching you need to call this cleanly without adding seemingly unused hooks that could break during development.

**Comment by AdSchellevis** [comment]
You probably better add your own custom frontend template for your system and add the calls for your own system in there if you need to refresh components for your own system. 
(override the menu item, hook-in your own proxy component and keep that up to date)

Eventually we might look into an option to extend configd calls with plugins (add dependencies for example), but that's not very high on my list.

**Comment by kekek2** [comment]
Move squid plugins from services() to plugins_squid()

**Comment by fichtner** [comment]
ok, this can be even simpler: plugin_configure('webproxy'), no need for plugin_squid()

**Comment by kekek2** [comment]
Done

**Comment by fichtner** [comment]
Merging this as preparation for https://github.com/opnsense/plugins/pull/266 , but we need to tweak change a few things.

**Comment by fichtner** [comment]
Thanks! :)

**Pull request merged**
