### PR TITLE
Implement startTLS for ldap #1346

### PR DESCRIPTION
**Pull request by EugenMayer**
ignore the implementation in #1348 since it is a non-used replication

### CODE REVIEW

**Comment by EugenMayer** [comment]
This is untested, since i have yet not clue how to drive a test setup. I rather expect it to work, but not sure entirely because of #1348

**Comment by EugenMayer** [comment]
Just tested on my FreeBSD11, opnsense 17.1 server with `opsense-patch b9e4d0eb11811a2619126b33c8a39aa299002b7f` and it worked nicely.

The only thing i now need to re-verify is, that encryption was actually really used during the process, since i did not block 336 plaintext yet. Anybody has a good idea on how tot do that?

**Comment by fichtner** [comment]
We'll keep this in -devel for a bit, asking for broader testing. So far: thanks very much, this is great!

**Comment by fichtner** [comment]
whoops, that wasn't the master branch :D

**Comment by EugenMayer** [comment]
well we need for sure someone who can ensure startTLS is actually used, so either packet sniffing or a startTLS only server - just so we dont fool anybody here :)

**Comment by EugenMayer** [comment]
As far as i can see, the container select does not work in the form when startTLS is activated

**Comment by fichtner** [comment]
step by step, the picker needs the settings passed, see https://github.com/opnsense/core/blob/master/src/www/system_usermanager_settings_ldapacpicker.php

**Comment by EugenMayer** [comment]
this is seriously the 3rd dublication of the authentication code? Considering what we are talking about, that is .. bad ;/

**Comment by fichtner** [comment]
in other news I just got phpstorm up and running. great stuff, thanks for the recommendation!

**Pull request merged**
