### PR TITLE
Kea dhcp4

### PR DESCRIPTION
**Pull request by cpalv**
for #7949

### CODE REVIEW

**Comment by AdSchellevis** [comment]
It might be better to start with a simple PR for adding the mac vendor as mentioned in the original ticket, I do have doubts about trying to glue everything around reservations together in this page as we try to prevent side affects.

Making the `lfc-interval` optional (and changing the default) as part of a cleanup is also not great in terms of traceability.

**Comment by cpalv** [comment]
`lfc-interval` is a required field? I was attempting to address this [issue](https://forum.opnsense.org/index.php?topic=43485.msg216357#msg216357) mentioned in the forums.  The kea documentation also says that the LFC process is [necessary](https://kea.readthedocs.io/en/kea-2.6.1/arm/dhcp4-srv.html#why-is-lease-file-cleanup-necessary).  

There is already a setting for `Periodic DHCP Leases Backup` in `System > Settings > Miscellaneous` that when disabled I assume will clear the current lease file on poweroff, but this probably doesn't mean much for devices that do not reboot.  I am also not  sure how this setting works w/ Kea or if it only effects ISC leases.

Kea LFC does run as a separate process though and I'm not sure where or if it logs anything about the lease file cleanup.  So it is kind of magical as far as traceability goes. 

Gluing together the leases and reservations seemed like the most straightforward way to handle #7950 along with getting reservation info/status for #7949.

I may have tried to do too much in one PR.  I can tear this one down and try just the MAC vendor information if that's preferable

**Comment by AdSchellevis** [comment]
> `lfc-interval` is a required field?

And set by default, from the manual (https://kea.readthedocs.io/en/kea-2.0.0/arm/dhcp4-srv.html):

> ... The default value of the lfc-interval is 3600. A value of 0 disables the LFC.

>There is already a setting for Periodic DHCP Leases Backup in System > Settings > Miscellaneous that when disabled I assume will clear the current lease file on poweroff, but this probably doesn't mean much for devices that do not reboot. I am also not sure how this setting works w/ Kea or if it only effects ISC leases.

That's legacy isc only, handled via https://github.com/opnsense/core/blob/master/src/etc/rc.syshook.d/backup/20-dhcpleases

> I may have tried to do too much in one PR. I can tear this one down and try just the MAC vendor information if that's preferable

One step at a time would be better indeed, my time is limited and reviewing large blobs of code often cost more time than adding features ourselves.

**Comment by cpalv** [comment]
Ah, I must've glossed over that section.  I'll go ahead and close this PR and open another

**Pull request closed without merging**
