### PR TITLE
Firewall / Rules - allow per-rule adaptive timeouts

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi!
may close https://github.com/opnsense/core/issues/5487 i hope.
No existing code touched except `FormSetAdvancedOptions` to allow '0' as a value of Advanced fields.
Thanks!

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@kulikov-a some small cleanups in https://github.com/opnsense/core/commit/32831f9be2e03c44ca5b62014f593b612350c881  (pushed into a separate branch), if it's ok for you I'll merge it to master.

**Comment by kulikov-a** [comment]
@AdSchellevis completely OK )
just two questions if i may: there will be no objections later that 0, strictly speaking, is not positive int?)
for the future PRs, do I understand correctly that it is recommended to validate a field in a single IF statement? (I did separate checks on the assumption that it makes sense to report multiple validation errors if applicable. like setting` adapative.start` to 0 end leave `max` and `adaptive.end` empty)

**Comment by AdSchellevis** [comment]
@kulikov-a the legacy code is still messy when it comes to validations, placing more in `if` `elseif` makes it a bit easier to read, although still not perfect.  you're right about the positive int part, let me change that back. just tried to align the messages a bit, overlooked the zero part here.

**Comment by AdSchellevis** [comment]
merged in https://github.com/opnsense/core/commit/b01da7a918ced0ab53871ce99bb2661db25cb650

**Comment by kulikov-a** [comment]
@AdSchellevis thanks!

**Pull request closed without merging**
