### PR TITLE
Sidebar - fix for too long a-link list

### PR DESCRIPTION
**Pull request by opnsenseuser**
if there is not enough space in a list of links upwards, the list moves down by the number of menu entries. so the problem with too many entries should now be solved. I hope that suits you. if so, please test. Thank you

### CODE REVIEW

**Comment by opnsenseuser** [comment]
grafik

**Comment by kulikov-a** [comment]
Hi
may i ask which editor are you using? all spaces are replaced with tabs?
as a result, the entire file is perceived as new -  need to read the entire file in search of 2 lines of changes)

**Comment by kulikov-a** [comment]
I have the opposite problem
menu
can the `(currentHeight > winHeight)` condition be slightly changed?

**Comment by opnsenseuser** [comment]
if there is not enough space "down" it should already pop "up" and if there is even not enough space it should now move down by the number of menu entries!

**Comment by opnsenseuser** [comment]
i think 

grafik 

is the problem. you can´t read the last line because the https...... overlaps it.

**Comment by opnsenseuser** [comment]
@kulikov-a i changed this

**Comment by kulikov-a** [comment]
@opnsenseuser 

> you can´t read the last line because the https...... overlaps it.

yes and not only. even when the status line disappears (although this is already inconvenient) the last menu item (in this case Web Proxy) is half hidden behind the browser window. Therefore, I propose to pop the menu up if the "current" and "win" heights differ by less than the height of one menu item

>  i changed this

thanks!!

**Comment by opnsenseuser** [comment]
if I did not miscount, then 34 plugins are now mutually exclusive with a resolution of 1080. that should be enough for now. 
grafik

**Comment by opnsenseuser** [comment]
@fichtner any change to get this into master? Or do you think we need a better solution? Only alternative way is to use a scrollbar. But i want to avoid that because it would be more usability friendly. And compared to freenas or pfsense it would be something different in the operation. What do you think about this? regards rené

**Comment by opnsenseuser** [comment]
I am still of the opinion that the services could also be divided. So make subdivisions in the service folder according to e.g. DNS services, proxy services, tools, etc. Regardless of this, the list at opnsense and also at pfsense is far too long and should be divided. But that's just my point of view.

**Comment by AdSchellevis** [comment]
@opnsenseuser let's try this on master and see how it goes. thanks

**Comment by opnsenseuser** [comment]
For what reason was the update not adopted in the current version of opnsense?

**Comment by fichtner** [comment]
The rule of thumb is core changes go on development release for one cycle.

**Comment by opnsenseuser** [comment]
ok, i see...thx

**Comment by opnsenseuser** [comment]
@fichtner I have a question and please don't be angry. I just wanted to know whether the sidebar will go online with the next release? Please don't get my question wrong. If not, I just wanted to know if I had to change something or made a mistake or the sidebar doesn´t work properly and this is the reason that you didn't release the update. 
i would just like to know, because maybe i can improve something in the future!

Thanks for the info and have a nice day - best regards, rené

**Comment by fichtner** [comment]
We wanted to do the larger rework of #4500 first to finish the proper menu reload even when sidebar is active. A number of vars are attached to the old menu so after reload nothing works anymore as you noted yourself.

**Comment by opnsenseuser** [comment]
@fichtner Is there anything i can do to help you?

**Pull request merged**
