### PR TITLE
Sidebar   fix for some problems with sticky sub submenu

### PR DESCRIPTION
**Pull request by fabianfrz**
cleaned up #2872, but I am unable to merge it back / create a pull request to rene´s repository.

@opnsenseuser please check if the memory issue still applies. I've run auto format on the code, so it is cleaner and I removed some redundant code.

### CODE REVIEW

**Comment by opnsenseuser** [comment]
@fabianfrz 
@fichtner 
unfortunately no real difference. I leave it as I wrote it. Then I understand it easier and can understand it a bit easier ;-)
I hope you are not angry with me. :-(
In any case very interesting how to write jquery optimized.
But thanks Fabian for your support. I suspect that it depends heavily on which side I am in opnsense. on the dashboard I have 6 columns active, this is also the traffic widget, etc. I also try to provoke the navigation to the utmost during the test and drive with the mouse wildly and very fast over all subemnüs up and down. I suspect there are several things that come together. performance number of widgets, etc.
Anyway ... I would like to thank you again for your support and wish you a nice weekend. best regards rené

**Comment by opnsenseuser** [comment]
@fabianfrz 
@fichtner 

I have now tested further and found the following:
the reason for the load is not on the sidebar but on the real-time data of the individual widgets such as cpu, traffic, etc. all that gives real-time data affects the sidebar but also the normal navigation quite negative. Of course I never noticed 6 columns full of widgets before. but all users who use only weak cpu's will probably never be able to benefit from the full scope of opnsense without sacrificing significant performance.

In my opinion, would have to partially optimize the reporting, the traffic, cpu widget to get here even with low cpu performance appealing results.

reagrds rené

**Comment by fichtner** [comment]
merged via 42beaef3aa464c8, thanks!

**Comment by opnsenseuser** [comment]
Thx Franco for mergin
Would be also great if you could merge the tukan and cicada mods. They are also important for the sidebar mod
https://github.com/opnsense/plugins/pull/953

Thx, regards rene

Regards,
Rene

Sonntag, 4. November 2018, 18:13 +0100 von notifications  <notifications@github.com>:

**Pull request closed without merging**
