### PR TITLE
Firewall: Settings: Advanced - defaults/placeholders

### PR DESCRIPTION
**Pull request by NOYB**
Get the actual system default for Firewall Maximum Table Entries and Firewall Maximum Fragments.

### CODE REVIEW

**Comment by NOYB** [comment]
Leave a commentIt's not a fix to "the fix".  Really has nothing to do with the fix.  Have had this for quite some time.  Just thought this would be a good time to submit it, and it happens to involve "the fix".

**Comment by fichtner** [comment]
Shall I close or do you want to rework it? I'm unwilling to help shape your proposals since you:

1. Are allergic to code review.
2. Imply people should have a thicker skin.

We can play hardball, no problem.

**Comment by NOYB** [comment]
Simply submit an honest PR and you go off the deep end because it alters a recent fix in order to accomplish it's objective.  Could have not included that part but it would not work the same/as intended.  Then when I offer explanation you make personal attacks.
Dude you're losing it.  Get a grip.

This PR is not about "the fix" i.e. bumping the default.  It is about presenting defaults in the GUI that are currently suppressed when a user config value is present.  This requires altering ("choosing") more than "one file".

This was no code review.

Whether or not people should have thinker skin is a discussion more appropriate for the web forum.  And that's where it was.  But you have bring it here as a personal attack or as justification for you action.  Guess you can't handle people having views that you disagree with.

You're playing "hardball" over something so petty proves my point.  You're losing it and need to get a grip.  Stop the vindictiveness because your feelings got hurt over a previous botched "code review" and code butchering.

**Comment by fichtner** [comment]
> Simply submit an honest PR and you go off the deep end

Please don't wast your time with accusations and victim cards.

**Comment by NOYB** [comment]
As if you are so concerned about my time.  LOL

**Comment by fichtner** [comment]
Feel free to try again when you are in a better mood. :)

And next time please read this:

https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

I'm going to spell it out for you: if you have a solution, prepare to bother talking about the actual problem. Not everyone is as smart as you are it seems.


Cheers,
Franco

**Comment by NOYB** [comment]
Yup.  You can't take being corrected.  Pointed out a legitimate bug due to failure to follow specifications and you tried to down play it.  As I recall trying to pass the buck because the code came from a third party.  So you get hurt feelings when I don't let you make excuses.

**Comment by fichtner** [comment]
> Yup. You can't take being corrected.

Stop barking, it has no effect.

> Pointed out a legitimate bug due to failure to follow specifications

If you're a genius, you need to communicate it. Now you just make up words like "specification" without backing them up with facts.

> As I recall trying to pass the buck because the code came from a third party.

Please explain. This means nothing without context.

> So you get hurt feelings when I don't let you make excuses.

You have made several miserable days for me. And you are a bad person for doing so.

**Comment by NOYB** [comment]
Yes it was a failure to follow specification and yes I provided the backup.  It's all in the thread.  You and everyone can read it there.  But I realize you are trying to insert your own altered reality.

**Comment by fichtner** [comment]
Likewise. Please let it go.

**Comment by NOYB** [comment]
Dude.  You're the one holding the grudge and attempting to exact revenge.  You are the one who needs to let it go.  You should have let it go a long time ago instead of letting your feelings get the better of you, behaving unprofessionally and hindering your product.

**Comment by fichtner** [comment]
You're still here and being unfriendly. I don't know why. :)

**Comment by NOYB** [comment]
Yeah but I know why you're still here and being unfriendly.

You make personal attacks, exact revenge and then call me unfriendly.  LOL You just continue to confirm Reddit.  They pegged you spot on perfectly.  I couldn't believe it until now.  You are doing exactly what they said you do.

**Comment by fichtner** [comment]
You are deflecting, most likely because you have nothing more to say.

Think of all that energy instead being put in your PRs. You can only change yourself. :)

And remember I said play hardball. I meant it. If you want me to stop just ask.

**Comment by NOYB** [comment]
What I want.  And always have wanted is for you to be professional.  A big part of that is having honest, open, no personal dialog about code.  Not lashing out because someone challenges you.  I made non personal response to your code reviews, citing PHP manual and that cause you to be unwilling to work with me.  Very unprofessional.  Like I said earlier.  Can't have an honest dialog with you about the code.

**Comment by fichtner** [comment]
I concur about the first part. I disagree about the second part. There are a number of people all over the world with varying degrees of knowledge and past experiences. They can successfully contribute. I would say this is one of the strengths of this community.

A particular example of when this does not work could mean two things: I'm lying or there is some truth to what I'm going to say.

Call me whiny or unprofessional or whatever you want. The truth is I don't see the point of working with difficult, stubborn people who have no regard for the time they are given by others because in the end there are better things to do here, at work, or elsewhere in life.

Communicate more concise. That means your PRs should give a full scope of what you are trying to do and which problem it solves. Or at least point to the forum thread.

Accept your role. For now at least, I'll have to do the review and be the difficult one whether you like it or not. I personally do not like it if that process goes south like in this case. So if we don't do this, no code will be merged and I don't think that's your goal. And besides, far too much problems have arisen from prematurely merged PRs over the last 15 years that added unnecessary code, spurious wrappers, premature caching mechanisms and so forth. To be precise, creating a JSON file is an explainable addition. Notice this is the first time "JSON" comes up and where we are. I don't think this is necessary, but it's your duty to explain and advocate its use. Not mine.

Above all, stay friendly. Life is too short for unpleasant contributions.


Cheers,
Franco

**Comment by NOYB** [comment]
I wasn't referring to this PR.  But several previous where you made bogus code changes and your explanations where incorrect.  When questioned about it and your response was to be unwilling to work with me.  It was not about the PR justification but your unwillingness to have honest dialog about your code changes to the commits.  Several which where just plain wrong.

**Comment by NOYB** [comment]
"

> Above all, stay friendly. Life is too short for unpleasant contributions.

"
After your personal attacks, that's pretty funny.

**Comment by fichtner** [comment]
Since you don't want to at least accept a grain of responsibility and you keep degrading the discussion after I offered a structured criticism I'm closing this now. Arguing with you is pointless as stated elsewhere. And you are not interested in constructive criticism, you just assume that everybody else needs to do whatever you want. Here's the short version: I will not put up with you anymore.

If you want to change something, please try to be a better person. After you've degraded my character a few times now, you mean realise that I'm less than perfect and at least try to work on it. :)


Good-bye,
Franco

**Pull request closed without merging**
