### PR TITLE
Fix Activity.

### PR DESCRIPTION
**Pull request by kekek2**
System/Activity don't show processes,

### CODE REVIEW

**Comment by fichtner** [comment]
@kekek2 can you explain "don't show processes" ?

**Comment by kekek2** [comment]
screenshot

**Comment by AdSchellevis** [comment]
@kekek2 which version is this? On my end it looks normal.

**Comment by kekek2** [comment]
17.7.12

**Comment by AdSchellevis** [comment]
That does the following display on a terminal at your end?

`top -aHSn 99999 `

**Comment by kekek2** [comment]
top

**Comment by AdSchellevis** [comment]
@kekek2 your using zfs?

**Comment by kekek2** [comment]
ZFS in the testing state.

**Comment by AdSchellevis** [comment]
that's where the extra line came from, we should probably search for the header rule differently to make sure it always works.

**Pull request closed without merging**
