### PR TITLE
Network Interfaces Settings: Fix loading and saving hardware options

### PR DESCRIPTION
**Pull request by OliverO2**
Addressing https://github.com/opnsense/core/commit/02d05f7278ccbfff6a2f3691d0663cb03c1767a8#r42427184

### CODE REVIEW

**Comment by AdSchellevis** [comment]
As mentioned here https://github.com/opnsense/core/commit/02d05f7278ccbfff6a2f3691d0663cb03c1767a8#r42437436 it seems I totally missed you changed the toggle logic, closing this now so a clean new PR can be opened to only split the config sections (as recommended earlier https://github.com/opnsense/core/pull/4271#issuecomment-675437544)

**Comment by OliverO2** [comment]
As noted here https://github.com/opnsense/core/commit/02d05f7278ccbfff6a2f3691d0663cb03c1767a8#r42442230, I'll be closing this and not going to pursue what I'd regard as a crippled solution with impaired usability.

**Comment by AdSchellevis** [comment]
ok, we'll leave it as is then, comment inline https://github.com/opnsense/core/commit/02d05f7278ccbfff6a2f3691d0663cb03c1767a8#r42453197

**Comment by OliverO2** [comment]
Referring to the inline comment https://github.com/opnsense/core/commit/02d05f7278ccbfff6a2f3691d0663cb03c1767a8#r42453197

> There might have been a miscommunication somewhere, but the solution itself does not work. Reversing logic needs changes on the parsing part as well (with additional chances on regressions).

With the added commit in this PR, the solution is working and has been extensively tested.

> Maybe it's for the best if we leave it as is, we currently can't afford this level of guidance.

If you don't have the motivation and/or resources to accept contributions, you could just state that you'd rather not take PRs.

The way this went was not just simple miscommunication, it's been a terrible onboarding experience for a contributor. I went the extra mile to solve a real pain point for users, touching legacy code that probably won't receive any maintenance otherwise.

What did I get back?

* First the go-ahead on a completely specified solution...
    * https://github.com/opnsense/core/pull/4271#issuecomment-685829611
        > The format itself looks workable
* ...then rejecting exactly that, making the entire investment a total loss:
    * https://github.com/opnsense/core/commit/02d05f7278ccbfff6a2f3691d0663cb03c1767a8#r42437436
        > we're nog going to swap all the toggles as discussed earlier, it seems I totally missed the reversal of the checkboxes, I'll revert the commit (8855e26)

       (Hmm, it was me after all who took the pain of dealing with the dysfunctional toggles, while avoiding to touch the stored configuration as requested.)

* On top of that, some disparaging comments:

    * https://github.com/opnsense/core/pull/4271#issuecomment-675437544
        > Changing the language may sound nice
    * https://github.com/opnsense/core/pull/4265#issuecomment-694854633
        > is tedious enough as it is
    * https://github.com/opnsense/core/commit/02d05f7278ccbfff6a2f3691d0663cb03c1767a8#r42427083
        > all-glitter-no-effect text
    
* And a bit of belittling users:
    * https://github.com/opnsense/core/commit/02d05f7278ccbfff6a2f3691d0663cb03c1767a8#r42427083
        > users will ignore it anyway

Any sound reasons given for the rejection? Not at all. 

So you'd rather keep me guessing: Any contribution guideline violated? Not to my knowledge. Was this more likely to introduce regressions compared to other changes in OPNsense? Probably not. Would it impede maintenance? Probably not (legacy code).

Was there really that much to lose here? Probably not. Was there something to win? A better user experience with understandable positive logic and precise explanations, hopefully preventing first-time users from struggling with a frozen network.

What I've been missing here is more respect for people on the other side of the fence. I really hope you'll be able to change that.

**Pull request closed without merging**
