### PR TITLE
mvc: regex conditional for UnqiueConstraint to fix #6775

### LINKED ISSUE #6775: CARP: Can not use the same link-local address for multiple CARP VIPs
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [ x ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [ x ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

I'd like to use fe80::1/64 as CARP address on all of my networks, but there is a unique constraint on the field, so it fails to validate.

**To Reproduce**

Configure 2 CARP VIPs with fe80::1 as address (on different interfaces, of course).

**Expected behavior**

As a rule, a unique constraint is a good idea here, but it should exclude link-local addresses on different interfaces.

**Describe alternatives you considered**

Just omit the check, as it was in earlier versions.

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.4.1-amd64
FreeBSD 13.1-RELEASE-p7
OpenSSL 1.1.1u 30 May 2023

### PR DESCRIPTION
**Pull request by fichtner**
Solution for unique constraint extension based on `addFields` extension with conditional regex matching. If this works for @AdSchellevis I will add a test case as well.

### CODE REVIEW

**Comment by fichtner** [comment]
@AdSchellevis if you say know I have time to rework :)

**Comment by AdSchellevis** [comment]
@fichtner How about changing the exclude format to something like:

`<filter><subnet> /^fe[89ab][0-9a-f]:/i </subnet><interface>.*</interface></filter>`

Although not totally sure what the regex for interface should be, but it would make the filters very explicit.

**Comment by fichtner** [comment]
Conceptually the match adds the field so the regex is a conditional extension for addFields. The match should either be on the anchor element (subnet value) or the full unconditional unique key of addFields -- but the latter is hard to control with complex unique keys if that ever happens. I've tried to use XML attributes but they disappear quickly in the constraints handling. Maybe that would be the most explicit solution. Rewriting the handling for addFields would also be possible to next filters inside: `field1` as general container.

**Comment by AdSchellevis** [comment]
The addFields construction didn’t take this kind of filters into account. I guess the issue is that in some cases you just want to exclude a specific value from the list (Stephan’s original issue if I’m not mistaken) and sometimes the constraint has a hard relationship with the fields added. 

My thought was if we make the target explicit for the exclusion, it would be much easier to read. Though I am still struggling a bit with what this filter should offer, in theory for this example it should add a token (interface) for all subnets matching the regex to determine uniqueness. In which case it would be more logical if addField could contain a condition inside the same construct. I’m just not sure if this could fix the other issue as well.

Looking at the code, I think it’s more about how the user/developer should define this than what it’s currently doing (which is probably fine, just need to check if Stephan’s use-case fits as well)

**Comment by fichtner** [comment]
Ok, Stephan’s issue was entirely different: treating a special value as the blank value (“dynamic”) in this case. We discussed it this week and the best way to avoid the problem is migrate the “dynamic” value to a blank value “” in line with the model. That makes an extension unnecessary.

What I’m trying to do is to extend the construction of the primary key based on real word condition (link-local multiple addresses allowed but need @intX appended to be unique). If it’s too special maybe better to do the model validation manually, but the unique constraint handles 80% of the code already it doesn’t make much sense not to extend it and copy+even extend it.

Yep, it’s a presentation issue first and foremost. Either we can try to allow attributes for each field or we restructure addFields to make it easier to extend:

`<addField><name>interface</name><parentMatch></parentMatch></addField>`

and support multiple addField nodes, maybe even in addition to keeping addFields. And I’m not tied to addField or name or parentMatch at all… whatever makes the most sense and is easy to use. 😊

**Comment by AdSchellevis** [comment]
That sounds good indeed, stick the field to the condition, this should be relatively easy to fix and explain.

**Comment by fichtner** [comment]
Hmm, I can't get getOption() to deal with "array" values in XML so multiple fields of `addField` are flattened to the last one. I'm doubting a bit if this is all worth it. The constructor comes all the way from BaseValidator.

**Comment by AdSchellevis** [comment]
I'm also fine by just fixing this in the vip model, but all things considered, all of this has quite a low priority and there are not a lot of similar issues we can reuse the same construct (that I'm aware of).

**Comment by fichtner** [comment]
Yeah, let's fix it in the model validation then.

**Pull request closed without merging**
