### PR TITLE
Create es_CO.po

### PR DESCRIPTION
**Pull request by piegope**
lang/es_CO: bring Colombian Spanish to 1% completed

### CODE REVIEW

**Comment by fichtner** [comment]
Hi Pier, very glad to see this. :) Do you agree to license your translation work under the 2 Clause BSD license?

**Comment by piegope** [comment]
Hello, glad to meet you. Yes, i agree to license my translation work under the 2 Clause BSD license.

**Comment by fichtner** [comment]
I hooked up the language file to the build system. We can enable this language's selection in the GUI when 30% is reached. How does that sound?

**Comment by fichtner** [comment]
And thanks! :)

**Pull request merged**
