### PR TITLE
Allow CNAME overrides for unbound

### LINKED ISSUE #1614: [17.1.6] Overrides for unbound can't be CNAME
Only A, AAAA and MX are options.
It would be nice to have at least CNAME also.  Maybe SRV and TXT too.

Usage example for CNAME.
host-a.vlan10.example.org A 172.16.10.123
host-a.vlan20.example.org A 172.16.20.123
host-a.example.org CNAME host-a.vlan10.example.org

### PR DESCRIPTION
**Pull request by sjorge**
We allow for CNAME to be used in the host override for unbound.

This closes #1614.

### CODE REVIEW

**Comment by fichtner** [comment]
looks good, thanks!

**Comment by sjorge** [comment]
Hey @fichtner although the CNAME are properly returned (yay) some revolvers seem to have issues with them.

This is because unbound does not include the recursive A and/or AAAA records :(
There is an excellent thread here http://unbound.net/pipermail/unbound-users/2009-March/000507.html

Looks like it will probably never work with unbound without having an authoritative server behind it.

**Comment by sjorge** [comment]
Example difference between dnsmasq with --cname=test.example.org,test.vlan10.example.org vs unbound with CNAME.

**dnsmasq**
```
$ dig +short test.example.org
test.vlan10.example.org.
127.0.0.2
```

**unbound***
```
dig +short test.example.org
test.vlan10.example.org.
```

**Comment by sjorge** [comment]
@fichtner bump

**Comment by fichtner** [comment]
yeah, agreed, I'll back it out.

**Comment by sjorge** [comment]
Yeah I switched back to dnsmasq for now, nothing wrong with it but I was initially realling impressed with unbound too.

**Comment by 3rd3** [comment]
@fichtner You wrote "CNAME does not fully work in unbound at this point". Might this be fixed/implemented in Unbound since?

This seems to be useful for e.g. safe search/content enforcement. Currently there is only a general switch/checkbox for that, but adding custom CNAME host overrides might allow for more granular control (in my case my client wants SafeSearch on Google and Bing but it has been found too restrictive on YouTube).

**Pull request merged**
