### PR TITLE
Virtual IPv6 prefix advertising on tracking LAN interfaces, add help …

### PR DESCRIPTION
**Pull request by maurice-w**
As discussed in #3310.

### CODE REVIEW

**Comment by fichtner** [comment]
This is relevant for DHCPv6/Router Advertisements, not for interfaces in general. Also better suited in the documentation.

**Comment by maurice-w** [comment]
It just doesn't seem intuitive that VIP functionality depends on this setting, so a hint somewhere in the UI would be helpful. But if you'd rather enable VIPs in automatic mode (as I think you suggest in #3920), I'm all for that.

**Comment by fichtner** [comment]
Added support for VIPs in automatic case in master

**Comment by maurice-w** [comment]
Did a quick test with 20.7.a_43 and it seems to work. Thanks!

**Comment by fichtner** [comment]
Yay, thanks for testing. ❤️

**Pull request closed without merging**
