### PR TITLE
dashboard: add page reload on successful save

### PR DESCRIPTION
**Pull request by Monviech**
When trying out the new dashboard, the save button didn't give me any feedback on successful save. So I have added a page reload.

### CODE REVIEW

**Comment by swhite2** [comment]
While this would certainly work with the least amount of code, the intent of the original design is to keep everything as dynamic as possible. This action will interrupt the keep-alive sessions collecting data.

I think this is fine for now, though perhaps there is a less invasive way we can think of to let the user know the action was succesful. Any opinion? :)

**Comment by Monviech** [comment]
Hello, we could also display a success message in a HTML message area, or make the save button vanish upon successful save, e.g. only reloading the area with the buttons?

I just replicated the behavior of the Restore Defaults button with the full reload of the whole page.

**Comment by swhite2** [comment]
Yes, the restore defaults was the only exception here, although in theory only the widget positions and width/height need to update with the current logic, this has a lower priority.

> we could also display a success message in a HTML message area, or make the save button vanish upon successful save, e.g. only reloading the area with the buttons?

If you can spare the time to propose something in this PR that'd be great - otherwise I'll add it to my todo list and merge this one for the time being.

**Comment by Monviech** [comment]
Sure I can try.

**Comment by Monviech** [comment]
@swhite2 What do you think of this idea? I think it fits to the general responsiveness of the new dashboard. Though, if it's not what you want, I'm open to change things, or pass you the torch on this. ^^

**Comment by Monviech** [comment]
Thanks for the feedback. Yeah that makes sense. 

I cant continue here until next week. If you need to work on the file I suggest you merge or close the PR, and we can fix the action and timeout sequence later.

**Comment by swhite2** [comment]
I'll change it in this PR in a bit and merge it after. Many thanks for the initial code.

FWIW, the dashboard is under active development so if you have any other feedback or changes, all welcome :)

**Comment by swhite2** [comment]
@Monviech Got a bit carried away with the styling part here.. sorry about that ;)

**Comment by Monviech** [comment]
@swhite2 Hey it looks interesting and like you had fun. :D Im going to try it out on the weekend. Thanks ^^

**Pull request merged**
