### PR TITLE
Correct settings in mpd.conf Host-Uniq

### PR DESCRIPTION
**Pull request by polxmod**
fixed command in pppoe configuration, connected to pull request #1730 https://github.com/opnsense/core/pull/1730

### CODE REVIEW

**Comment by fichtner** [comment]
@polxmod can you try https://github.com/opnsense/core/commit/c909149e519bac878fab98417db38e3dd300da61 ?

**Comment by fichtner** [comment]
0d9e0ba6167 is also needed to lower-case the hex string according to the manual.

**Comment by polxmod** [comment]
@fichtner I've tested the patch:
```
opnsense-revert opnsense
opnsense-patch c909149
opnsense-patch 0d9e0ba 
```
and it works, I can connect.

thank you

**Comment by fichtner** [comment]
super, I will get this into OPNsense 17.7 which comes out next week. spread the word, and many thanks! :)

**Pull request closed without merging**
