### PR TITLE
Fix anchor name quoting

### PR DESCRIPTION
**Pull request by evbevz**
To have possibility in plugins to set anchors:
anchor myanchor quick
or
anchor "myanchor/nested" quick

Quoting of anchor name is auto-fixed if slash exists in anchor name.

### CODE REVIEW

**Comment by fichtner** [comment]
something looks off here even in the code that we have... why does it matter how this is quoted? what do we do here that is not desired?

**Comment by fichtner** [comment]
or is this about the attribute "quick" being mishandled?

**Comment by evbevz** [comment]
man pf.conf:
Optionally, anchor	rules can specify packet filtering parameters using
     the same syntax as	filter rules.  When parameters are used, the anchor
     rule is only evaluated for	matching packets.  This	allows conditional
     evaluation	of anchors, like:

	   block on $ext_if all
	   anchor spam proto tcp from any to any port smtp

So, there are many different additional parameters can be with anchor.
Simplest solution is to make quoting in right way.

**Comment by fichtner** [comment]
but the quoting is done to prevent this, a safety measure as you will, because we only ever intended to pass the name. if we want to do it right, we can't simply pass the string as is... what happens on "\n" ? are we going to inject other rules after a newline?

**Comment by evbevz** [comment]
I think that plugins subsystem is developers area. It is not place, where strings goes to configuration from web-interface. If developer wants to break system, he can do it.
I thought that there is synthax check here for anchor name quoting.

**Comment by fichtner** [comment]
The question is simple... how much flexibility do you need? We don't have to change the world in one day. If you only use quick here, we should add support for quick.

We don't want to restrict -- we want to provide safe constraints to develop within. For everthing else there is pf.conf. Because if not, these cases will bite us back during support hours. The developer who "broke" it will be gone, but someone else will have to find out what went wrong and users won't know how to debug. And if we support verbatim strings who does the validation of the rule syntax in them? Can we be sure the rules can't be manipulated by the user in a bad way through a config field on the GUI that allows adding unintended side effects to this?

**Comment by evbevz** [comment]
Yes, I need only quick parameter.

**Comment by fichtner** [comment]
does this work for you? f4acddb

**Comment by evbevz** [comment]
Franco, it's good. Merge ancor_quick branch and delete my pull-request.

**Comment by fichtner** [comment]
@evbevz thanks, done :)

**Pull request closed without merging**
