### PR TITLE
Aliases: show available room in table-entries limit

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi!
in continuation of the https://github.com/opnsense/core/issues/5127#issuecomment-892399166 discussion
-show progress bar with overall count (including failed tables length) vs. `table-entries` limit
-send error msg to syslog on table (re)load error
-write stats file ((so api call executes faster)) to aliases db dir with alias name, alias size, alias extra size, pfctl errror message

### CODE REVIEW

**Comment by Actpohomoc** [comment]
Thank you for very good work! I will try to download your files to test and try your very interesting features.

**Comment by kulikov-a** [comment]
@Actpohomoc thanks! 
easier to test with `opnsense-patch -a kulikov-a 72ad80b 6ba8244 76de566 9719a8d f106c8d` (need to restart configd service after patch so new action can work)  and revert with the same command )
and please note that this is a draft pr for discussion only.

**Comment by fichtner** [comment]
Revert only works in reverse order if multiple patches are given! 😉

**Comment by AdSchellevis** [comment]
@kulikov-a changed it a bit in https://github.com/opnsense/core/commit/9b31fad9ed04b7c04423aa007b0ba64ebc9221a0, what do you think? (made it a bit simpler, removed the additional error log and moved the progress bar on top)

**Comment by kulikov-a** [comment]
@AdSchellevis almost complete rework ) 
I like it!
 just a couple of things:
if I understand correctly, now pftablecount.py does not take into account the size of the tables that are not in the /var/db/aliastables/? (bogons, external etc). 
I'm not sure about arithmetic: if the size of the table has decreased, but for some reason there was a loading error, is it correct to choose a larger value?
and small question on html part: 
maybe it is worth to describe both parts of the fraction in the tooltip?

**Comment by AdSchellevis** [comment]
> @AdSchellevis almost complete rework )
> I like it!

Thanks!

> if I understand correctly, now pftablecount.py does not take into account the size of the tables that are not in the /var/db/aliastables/? (bogons, external etc).

Thanks for the fix, that was indeed the intention.

> I'm not sure about arithmetic: if the size of the table has decreased, but for some reason there was a loading error, is it correct to choose a larger value?

The idea is rather simple to be honest, let's say we try to load 2M records in a 1M reservation. If we weren’t able to do so, the actual reservation of the table equals 0 (loading error). So if we always count the intended amount (planned) when it's higher than the actual size, we can easily report the overallocation (used for more than 100% likely needs an increased reservation). 
There are some small downsides to this approach, but I do believe these are less problematic than the issue we're trying to fix, if `pfctl` optimises the table, the actual usage might be slightly lower, manual additions before apply clutter te view a bit as well.

> and small question on html part:
> maybe it is worth to describe both parts of the fraction in the tooltip?

Definitely, I was struggling a bit with the icon yesterday, figured you would take another look as well :) Thanks!

**Comment by kulikov-a** [comment]
@AdSchellevis 

>  but I do believe these are less problematic than the issue we're trying to fix, if pfctl optimises the table, the actual usage might be slightly lower, manual additions before apply clutter te view a bit as well

totally agree that the exact number of planned records can not be obtained by lines counting only but its still a useful visual info)

I think then the request can be considered closed?
Thanks again to @AdSchellevis !

**Pull request closed without merging**
