### PR TITLE
Firewall: Diagnostics: pfTables - alias_util.volt - margin fix

### PR DESCRIPTION
**Pull request by opnsenseuser**
Firewall: Diagnostics: pfTables - alias_util.volt - margin fix

only a small fix I noticed by accident!

screenshot:
grafik

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@opnsenseuser it's missing a bit of spacing indeed, I'll put it in a style and commit. If I'm not mistaken, it should be 2px, or not?

**Comment by opnsenseuser** [comment]
i think it´s 3px ?

**Comment by opnsenseuser** [comment]
@AdSchellevis I oriented myself to the distance between the "flush" botton and the "refresh" botton.

**Comment by AdSchellevis** [comment]
@opnsenseuser you're probably right

**Pull request closed without merging**
