### PR TITLE
Generate ssl options for IPv6 web configurator

### PR DESCRIPTION
**Pull request by ghostwheel42**
In lighttpd < 1.4.46 ssl options like ssl.use-sslv2 and
ssl.cipher-list have to be included twice.

### CODE REVIEW

**Comment by fichtner** [comment]
Merged, thanks! Closing the other one without merge as we copy over the master change in the different file anyway.

**Comment by fichtner** [comment]
@ghostwheel42 @sjorge hey guys, I'm working on strict IP binding for lighttpd and noticed this workaround is still there, but we've gone from 1.4.45 to 1.4.48... is this still an issue or can we remove this?

**Comment by fichtner** [comment]
@ghostwheel42 thanks, that's what I did subsequently since we went from 1.4.45 directly to 1.4.48. If you could check out opnsense-devel / master to double check that would be great. It works fine on my end.

**Comment by ghostwheel42** [comment]
@fichtner Sorry for the late answer. Yes, the new configuration works for me.

**Comment by fichtner** [comment]
@ghostwheel42 thank you 👍

**Pull request merged**
