### PR TITLE
Virtual IPv6 prefix advertising, add help text

### PR DESCRIPTION
**Pull request by maurice-w**
As discussed in #3310.

### CODE REVIEW

**Comment by fichtner** [comment]
I am not sure what @AdSchellevis thinks but if find this hint too circumstantial to be of use. It may be better suited for an IPv6 tutorial that deals specifically with ULA aw VIP to accompany a tracked WAN prefix.

**Comment by AdSchellevis** [comment]
I agree, better leave these things in the docs, either https://docs.opnsense.org/manual/firewall_vip.html explaining when/why this matters or as @fichtner suggested an additional tutorial page

**Comment by maurice-w** [comment]
This is not specific to ULAs or tracking interfaces, it affects any VIP on any interface (including static ones). They don't fully work until you manually restart radvd. This doesn't seem intuitive. Took me a while to figure it out. A hint in the UI would have really helped.

**Comment by AdSchellevis** [comment]
better keep this in the docs, although I understand it might help some it also triggers questions by others.

**Pull request closed without merging**
