### PR TITLE
Remove CPU Load Tooltip

### PR DESCRIPTION
**Pull request by marjohn56**
Remove tool tip from small CPU load system info widget.

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@marjohn56 better to remove, git knows the past ;)

**Comment by marjohn56** [comment]
Is done, I've added the word 'Average' to the large CPU graph though, it makes more sense there.

**Comment by AdSchellevis** [comment]
@marjohn56 I meant the comment lines in the commit ` /* Removed tooltip */`

**Comment by marjohn56** [comment]
Okey dokey.

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
