### PR TITLE
MVC View: add copy to mutliselects

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi
possibly closes https://github.com/opnsense/core/issues/4788
I'm not sure about the separator: I made a `\n`  because I use https://github.com/opnsense/core/issues/4497. Before FR review and in case of refusal, we can make a `,`
Thanks!

### CODE REVIEW

**Comment by fichtner** [comment]
Lovely idea. Maybe we can go a bit further and add a paste as well making the operations more like cut/copy/paste everyone knows?

**Comment by kulikov-a** [comment]
@fichtner nice to hear )
tokenize2 supports pasting but only with the specified delimiter (now it's a comma). Using a link, of course, we can check the separator and bring it to the desired value. I'll try to play with this

**Comment by kulikov-a** [comment]
@fichtner played with pasting and can't make compatible code (clipboard security, permissions etc):
on Chrome it works well with the Clipboard API's navigator.clipboard.readText() method but "Firefox only supports reading the clipboard in browser **extensions**" 
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText
`execCommand("paste")` also disabled on most browsers or works in extensions
can you suggest more ways? thanks!

**Comment by kulikov-a** [comment]
@fichtner @AdSchellevis 
Hi!
I have prepared a variant with the pasting possibility.
From the pros: we can insert, for example, a column from the Excel sheet without first changing the comma separator.
The downside is cross-browser compatibility. Checked on Chrome, Opera and FF. Chrome and Opera - everything works well. On FF, I simply do not display the paste link
How will it be more convenient? Do you want me to update the changes in this request or add a new one?
Thanks!
copy-paste

**Comment by AdSchellevis** [comment]
@kulikov-a I'm not sure, but if you post the code I'll take a look when I have some time available. The screenshot looks nice by the way.

**Pull request merged**
