### PR TITLE
Update Missing translations #463 

### PR DESCRIPTION
**Pull request by thelinuxfr**
Hi @fichtner , it's good ?

### CODE REVIEW

**Comment by thelinuxfr** [comment]
@fichtner  if I understand you, it's ok

**Comment by fichtner** [comment]
Almost, the second line is correct now, the first one doesn't need embedding of &lt;br&gt; via sprintf because it's not enclosed :)

**Comment by thelinuxfr** [comment]
@fichtner sorry, I do not understand you, an example?

**Comment by thelinuxfr** [comment]
@fichtner Hi, where were we ? I'm lost :D

**Comment by fichtner** [comment]
Hehe, I'll merge this manually tonight and update the parent ticket. No need to do anything else but ping me if I forget.

**Pull request closed without merging**
