### PR TITLE
Allow to configure SSH setting PubkeyAcceptedAlgorithms via GUI

### PR DESCRIPTION
**Pull request by 8191**
As OpenSSH 8.8 disables RSA signatures using the SHA-1 hash algorithm
by default some older SSH clients might not be able to connect to
OPNsense anymore. Therefore, it might be needed to manually modify the
PubkeyAucceptedAlgorithms sshd config option.

### CODE REVIEW

**Comment by fichtner** [comment]
Older clients should really be updated since RSA can still be used in safe forms with the new server. The clients that can't must be updated.. I think this is unnecessary, but it's up to @AdSchellevis to merge.

**Comment by AdSchellevis** [comment]
let mature this for a while and see if more people will ask for it, to me this feels a bit unnecessary too.

**Comment by 8191** [comment]
> Older clients should really be updated since RSA can still be used in safe forms with the new server.

From a security and a policy point of view I totally agree here. But from a real-life point of view, I believe we need to admit that things work differently. :-(

I faced this very situation yesterday as I recognized that one of my development tools ships psftp in version 0.74 which was actually released last year (2020-06-27). The tool is hard-bundled and cannot be changed, so I rely on the upstream project to update PuTTY in there. Support for newer signature methods such as rsa-sha2-256 and rsa-sha2-512 was added to PuTTY in version 0.75 (2021-05-08). That means - as I see it now - that after less than one year of transition period OPNsense is already retiring a quite common SSH client which is not up to date.

I fully agree, that the default setting should not be changed (i.e. ssh-rsa _should be disallowed_ per default), but one should be able to intentionally activate insecure algorithms.

**Comment by fichtner** [comment]
> That means - as I see it now - that after less than one year of transition period OPNsense is already retiring a quite common SSH client which is not up to date.

We do follow the best practices of the bundled software. This isn't our fight and I don't want to start release engineering things like OpenSSH just for portability while also undermining the authors intent for the software's security.

That being said your patch is the best middle ground here for the problem you described. I think we can agree on that.

If we could hide these overrides under an advanced knob that would be my preference as this tries to bridge a gap that is limited in time and I don't want new installs making all these decisions when OpenSSH comes with a sensible default for most users even in the newest releases.

What do you think?


Cheers,
Franco

**Comment by 8191** [comment]
> I don't want to start release engineering things like OpenSSH just for portability while also undermining the authors intent for the software's security.

I can understand that at one hand, but at the other hand OPNsense provides a frontend for these tools (such as OpenSSH) and the authors of those tools, such as OpenSSH, make their decisions without the OPNsense frontend in mind. The author's intent was maybe (I'm speculating) to deprecate the RSA-1 algorithm, having in mind that there is a config option enabling it. - Well here we are building that option.

I totally agree with your idea not to provide too many settings on the UI which are only needed by a fraction of users. I've modified this PR to hide all cryptographic settings (also the existing ones for _Key exchange algorithms_, _Ciphers_, _MACs_ and _Host key algorithms_. I believe 99% of the installations should be fine with the provided OpenSSL defaults.

**Comment by NOYB** [comment]
ONPsense 21.7.5 broke several SSH tools.  Short list just to name a few: PuTTY 0.75, Wireshark 3.4.10, GIT Extensions 3.5.4 (PuTTY 0.75), and WinSCP 5.19.4, 

PuTTY 0.76 works
Wireshark 3.6.0 works
GIT Extensions 3.5.4 configured to use PuTTY 0.76 works
WinSCP 5.20 release with PuTTY 0.76 is due any day now and should work.

Trouble with the wait and see how many people complain approach is that for every person who complains there are many more impacted who don't.  "Where there's smoke there's fire."

**Comment by AdSchellevis** [comment]
People will always have to change something (clients, toggles on our end, ..), waiting a bit to see how useful a feature is (that lowers security) usually isn't a very bad idea. It's quite easy to stuff toggles in, removing them later to keep code maintainable is often difficult and comes with a lot of noise. Security is also about keeping code maintainable and making it more difficult to use non-safe options.

Again this doesn't mean we won't add it, just that we wait a bit to see how much it's actually needed.

**Comment by fichtner** [comment]
Well, we heard the side where some utility we don't even see doesn't work with some other utility we happen to provide. And here is the flip side of providing these overrides: https://forum.opnsense.org/index.php?topic=25574.0

**Comment by 8191** [comment]
@fichtner Well, even that case is related to these crypto overrides, this basically might happen with each single setting. We'd need to check each single setting after an update of an upstream component where OPNsense generates configurations for.

Before this PR gets merged this learning should be considered and the configd template should take into account that crypto settings might disappear.

**Comment by fichtner** [comment]
This doesn't scale and provides no fallback for options that have gone away even if we can catch this behaviour. Complaints will always be complaints no matter how much effort is spent here.

**Comment by fichtner** [comment]
@8191 I do appreciate your motivation to get the problematic bits out of the way. :) Eventually such changes need a place in the actual template/backend framework to happen automatically for all services, but this is more of a legacy vs. MVC service handling issue and the complexity for OpenSSH is low enough to keep it on the legacy end of the table.

Lockouts can still occur due to settings being removed upstream so the remaining question is how to present this in the GUI? We don't have to solve it now, but it would be interesting what you think about it?

**Comment by 8191** [comment]
I actually thought about migrating the SSH config to a configd template, but refrained from it to not blow up this rather simple PR. ;-) Yes, I agree, this is nothing specific for OpenSSH it applies to all 3rd party services.

The presentation on the GUI is a valid point. With my proposed solution startup does not block, but the user never recognizes that the actual SSH configuration differs from the intended configuration. Maybe we could show an exclamation mark next to the setting warning the user to revise the setting. I.e. as long as the config contains values not supported by the system, a warning appears next to the setting in the GUI.
@fichtner Do you think that's something beneficial here? Or just a fancy, but unneeded function?

For the situation that a complete config option vanishes maybe a solution might be to remove the setting itself (e.g. checkbox/dropdown), but leave the label and add an explanation how the removed functionality might be compensated otherwise - at least for some releases.

**Comment by fichtner** [comment]
> ONPsense 21.7.5 broke several SSH tools

Going back to this I think to be fair this should have read "several SSH tools when using RSA keys". The administrator should have issued and authorized complementary ECDSA or ED25519 keys in the meantime. Personally, I did create ED25519 keys for eventual migration away from RSA in March 2020 for my equipment and it works.

**Comment by fichtner** [comment]
@8191 In principle I agree with a markup for bad values, but in the meantime I would not want to do this for static PHP pages because in the end we would have to it twice. How about in the meantime we just log the values that no longer work? The next time the admin opens the page and saves it the values will be gone anyway.

**Comment by fichtner** [comment]
PS: I think we should get this into 22.1... it looks like a good improvement

**Comment by 8191** [comment]
@fichtner I've added the log line as a workaround for now. Maybe we can migrate the SSH configuration to MVC for the next major release (22.7?)...

image

**Comment by L1ghtn1ng** [comment]
Just to throw my 2 cents in here for SSH clients, if people need new ssh clients you can look at https://mobaxterm.mobatek.net/ or also https://www.termius.com/ if you need to do sftp you can look at https://cyberduck.io/ moba can do it built in. The reason I say we do not include this is this will be wide spread issue next year which in turn means software will get updated when you have Ubuntu22.04 the next version of fedora and so forth. This will be an issue with arch systems etc already. So I do not see the point in adding this myself. Also if you are on a newer version of win10 you have ssh built in so you can also use that. Hope that helps people

**Comment by fichtner** [comment]
merged, thanks!

**Pull request merged**
