### PR TITLE
MVC View: copy|paste on multiselect

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi!
a variant of https://github.com/opnsense/core/pull/4789 with pasting
I do it as a draft so as not to be confused
Thanks!

### CODE REVIEW

**Comment by kulikov-a** [comment]
@AdSchellevis thanks!!)

**Comment by kulikov-a** [comment]
ie11 compatibility added. sorry. I always forget to check

**Comment by AdSchellevis** [comment]
hehe, no problem, I'll try to take a look this weekend, it's a bit busy

**Comment by AdSchellevis** [comment]
@kulikov-a looks good, thanks! I've made some small changes (simplify some parts), can you try https://github.com/opnsense/core/commit/a1d05fe97a2bd4084c751f3cd8547cf6a0c26a64 ?

**Comment by kulikov-a** [comment]
@AdSchellevis tested, works, looks much cleaner. Thanks so much!

**Pull request merged**
