### PR TITLE
move from plugins: unbound debugging

### PR DESCRIPTION
**Pull request by fabianfrz**

### CODE REVIEW

**Comment by fichtner** [comment]
thanks, let me know when you want this pulled in. there is alignment work for #1491 that will likely shift / enhance these files as discussed.

**Comment by fabianfrz** [comment]
@fichtner this should be it for now, have fun.

**Comment by fichtner** [comment]
merged, thanks!

**Comment by AdSchellevis** [comment]
@fabianfrz @fichtner are we sure we want ruby as a core dependency? Personally I would rather stick to python or php, given the fact that both are used for all the other components.

**Comment by fichtner** [comment]
my task https://github.com/opnsense/core/issues/1505 as discussed with Fabian

**Comment by AdSchellevis** [comment]
Thanks! If you need help, just let me know.

**Comment by fabianfrz** [comment]
@AdSchellevis Franco wanted that to be moved to core from here: https://github.com/opnsense/plugins/pull/101

**Comment by AdSchellevis** [comment]
@fabianfrz I just missed the comment, sorry about that, I agree it's a good idea to move it to core.

**Comment by fabianfrz** [comment]
@AdSchellevis no problem. Nobody will see it anyway as there is currently no GUI for it ;)
It is made to make it possible to generate some diagnostics pages for unbound.

**Comment by AdSchellevis** [comment]
@fabianfrz nice!

**Pull request merged**
