### PR TITLE
Implemented wildcard includes for ipsec/strongswan

### PR DESCRIPTION
**Pull request by stumbaumr**
So this is the PR mentioned here
https://github.com/opnsense/core/pull/3298

It just adds wildcard includes to
ipsec.conf
ipsec.secrets
strongswan.conf

Best regards
Rainer

### CODE REVIEW

**Comment by fichtner** [comment]
does this require empty stub files or is it ok for strongswan if no files are present?

**Comment by stumbaumr** [comment]
It complains for some but does start...
```
...
-rw-r--r--   1 root     wheel       386 Mar 11 09:36 strongswan.mobile.conf
-rw-------   1 root     wheel        49 Mar 11 09:38 ipsec.mobile.secrets
-rw-r--r--   1 root     wheel      1178 Mar 11 09:45 ipsec.mobile.conf
-rw-r--r--   1 root     wheel       891 Mar 11 09:46 strongswan.conf
-rw-------   1 root     wheel        88 Mar 11 09:46 ipsec.secrets
-rw-r--r--   1 root     wheel       968 Mar 11 09:46 ipsec.conf
-rw-r--r--   1 root     wheel     17089 Mar 11 09:46 filter_tables.conf
root@opnsense01:/usr/local/etc # mv *.mobile.* /root/
root@opnsense01:/usr/local/etc # ipsec stop
Stopping strongSwan IPsec...
root@opnsense01:/usr/local/etc # ipsec start
no files found matching '/usr/local/etc/strongswan.*.conf'
Starting strongSwan 5.7.2 IPsec [starter]...
no files found matching '/usr/local/etc/ipsec.*.conf'
no netkey IPsec stack detected
no KLIPS IPsec stack detected
no known IPsec stack detected, ignoring!
root@opnsense01:/usr/local/etc #
```

**Comment by fichtner** [comment]
ok, thanks for the clarification :)

**Comment by stumbaumr** [comment]
Thanks for being so quick - this is really cool!!!

**Comment by stumbaumr** [comment]
This actually solves
https://github.com/opnsense/core/issues/3295
and
https://github.com/opnsense/core/issues/3300

**Comment by AdSchellevis** [comment]
@stumbaumr can you test https://github.com/opnsense/core/commit/a4d157db0bc622c68af6da717c311499d8362691 ? I've dropped the files in directories, which is more aligned with the standard samples that are shipped with the software on our end.

`e.g. /usr/local/etc/strongswan.conf.sample
`

**Comment by stumbaumr** [comment]
@AdSchellevis I created comments in your PR - there seems to be a mixup with directory names...

**Comment by AdSchellevis** [comment]
@stumbaumr oops, my mistake, it seems that I mixed them up indeed. take 2 --> https://github.com/opnsense/core/commit/dfd48d29349688d25b102b928ccbd509aa516f9a

**Comment by stumbaumr** [comment]
@AdSchellevis ok, now it works as intended.

**Comment by AdSchellevis** [comment]
@stumbaumr ok, thanks for confirming

**Pull request merged**
