### PR TITLE
Add TCP flags to firewall log

### PR DESCRIPTION
**Pull request by maloo1**
Hi, 
Not sure if you would consider this small change, but I find it very useful to have the TCP flags shown in the firewall log...
Thanks!

### CODE REVIEW

**Comment by AdSchellevis** [comment]
it would probably be better if one could hide/show columns, preferences differ between people, adding all options will make the screen quite crowded...

**Comment by fichtner** [comment]
There used to be a ticket for this. We should update the contribution template to search for closed tickets as well...

**Comment by fichtner** [comment]
Specifically, please consider this comment https://github.com/opnsense/core/issues/2195#issuecomment-634060680

**Comment by maloo1** [comment]
Yeah that would definitely be a better solution to be able to select which columns to show!! I can have a crack at doing this but my php is pretty average, but if your willing to provide feedback/guide me through the existing opnsense structure ill give it a shot!

**Comment by fichtner** [comment]
@maloo1 sure, we are happy to review. Most of it us UI/JS fiddling in this case so PHP won't get in the way ;)

**Comment by fichtner** [comment]
Closing this waiting for new PR.

**Pull request closed without merging**
