### PR TITLE
Cosmetic changes to Tunables section

### PR DESCRIPTION
**Pull request by Northguy**
There is a note at the bottom of the tuneables which states that some changes are applied directly and some require a reboot. 

In my opinion a more logical notification would be to show that sentence in the Apply notice box in stead of at the bottom of this page. That location can be easily overlooked.

### CODE REVIEW

**Comment by fichtner** [comment]
I agree with this, but we shouldn't kill two perfectly valid translations for a new string that is just a composition of the two. use "gettext(...) . ' ' . gettext(...)"

**Comment by Northguy** [comment]
Hi Franco, my lack of knowledge plays a part here. Is it possible to concatenate two of those strings easily? If so, I will make an effort to provide you with a new commit

**Comment by Northguy** [comment]
@fichtner I think I nailed it. Please check latest commits. Tested on my own system and it works.

**Comment by fichtner** [comment]
Looks good to me, thank you ❤️

**Pull request merged**
