### PR TITLE
JP translation 92% complete after stiching in prior work

### PR DESCRIPTION
**Pull request by dotike**
The home stretch for JP!  ひじょにまんぞく！
- Full attribution to original BSD copyright holders intact
- Full commit history intact for translation strings (Chie Taguchi)
- merged against current OPNsense .pot file using msgmerge

### CODE REVIEW

**Comment by fichtner** [comment]
Holy mother of translations. Great work, thank you!! :)

**Comment by fichtner** [comment]
@dotike small nitpicks:

https://github.com/opnsense/core/blob/master/lang/ja_JP.po#L1-L4
ja_JP.po:11428 (Send/Expect translation got lost... maybe intended?)

**Comment by dotike** [comment]
L1-4, totally a regression in all the merging of our old work, my bad.

--
This, I believe, is the intended translation, "Send/Expect",
https://github.com/opnsense/core/blob/master/lang/ja_JP.po#L11428

One of the lines in the source is:
$types = array("icmp" => gettext("ICMP"), "tcp" => gettext("TCP"), "http" => gettext("HTTP"), "https" => gettext("HTTPS"), "send" => gettext("Send/Expect"));

This is a case where a native Japanese speaker can disambiguate, the english term fits in clearly in the context of the rest of the list.

**Comment by fichtner** [comment]
ack, thanks for double-checking

**Pull request merged**
