### PR TITLE
Services - Unbound DNS - General - System Domain Local Zone Type Option

### PR DESCRIPTION
**Pull request by NOYB**
Expose system domain unbound local-zone type to be configurable.

### CODE REVIEW

**Comment by fichtner** [comment]
We should retain compatibility and use "transparent" as the empty default. I'll do this post-merge. Thanks!

**Comment by fichtner** [comment]
Please check 0bd1d466f064a1d7ba85b91831d0ae9e91e957e5

**Comment by NOYB** [comment]
It should already be using "transparent" as the default if the setting doesn't match a valid type.  That should include empty.  (unbound.inc)

**Comment by fichtner** [comment]
It does, but it previously forced "transparent" into the config.xml causing both "" and "transparent" to mean the same thing.

**Pull request merged**
