### PR TITLE
Fix error with domain "."

### PR DESCRIPTION
**Pull request by kekek2**
Another way

### CODE REVIEW

**Comment by AdSchellevis** [comment]
will also fail with `..string`

**Comment by kekek2** [comment]
screenshot
`root@opnsense:~ # grep blackList /usr/local/etc/squid/squid.conf
# ACL - Blacklist - User defined (blackList)
acl blackList url_regex xn--tst-qla\.de
acl blackList url_regex \.xn--tst-qla\.de
acl blackList url_regex \.
acl blackList url_regex \.\.xn--tst-qla\.de
http_access deny blackList
`

**Comment by tech62** [comment]
Any idea when this fix will be integrated to opnsense ?

**Comment by fichtner** [comment]
There is a patch in the 18.7 series. You can always install it manually from https://github.com/opnsense/core/commit/9ad0cbc1 via

    # opnsense-patch 9ad0cbc1

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/core/commit/2be29a51fffbc9e5b98011d382831fbe9c5c945c should handle the issue with multiple leading dots.

**Comment by tech62** [comment]
After add "facebook.com" and ".facebook.com", the proxy service wasn't want to start :/ (with or without this fix)

Version : OPNsense 18.1.13-amd64

> Jul 26 10:31:30 	root: /usr/local/etc/rc.d/squid: WARNING: failed to start squid
> Jul 26 10:31:30 	squid: Bungled /usr/local/etc/squid/squid.conf line 27: acl bump_nobumpsites ssl::server_name "/usr/local/etc/squid/nobumpsites.acl"

**Comment by AdSchellevis** [comment]
@tech62 this specific example has no relation with this fix, probably another configuration issue.

**Comment by tech62** [comment]
My bad, i've read "Fix error with domain "." and my proxy crashed when i type a domain with a dot at the start of the domain name like ".facebook.com"  in the sslbump field - hense the reaseon for my confusion

It's a fresh install and if i let this field empty, the proxy works.

Thanks for your help !

**Pull request closed without merging**
