### PR TITLE
firewall log widget: get description to compare

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi.
possibly closes https://github.com/opnsense/core/issues/4815
also moved logs fetching to first ajax call completition
can't figure out if a `$("#filterlogentriesinterfaces").val() == intf` comparison is required at all
Thanks!

### CODE REVIEW

**Comment by fichtner** [comment]
I'm kind of tripping over the lowercase match since we try to use uppercase everywhere so it would seem the controller makes some nonconforming naming decisions that probably also affect the firewall live log page. It might be better to move the required fix closer to the source of the problem?

**Comment by kulikov-a** [comment]
@fichtner to be honest, I do not quite understand why the `toLowerCase()` is used before the comparison. as well as why the comparison goes with `val()`. so I just decided not to touch it. I will test the behavior without a `toLowerCase()` .

eventually `#filterlogentriesinterfaces` can be filled on the client side with the same api call
moreover, if I understand correctly, it will not be necessary to convert the interface to a description for each log entry. we can compare directly the interface from the log entry with the `val()` in the `$("#filterlogentriesinterfaces").val()`

**Comment by kulikov-a** [comment]
@fichtner @AdSchellevis 
Hi. sorry, what is the likelihood that I will break something if I make  `strtoupper`  in `                $intfmap[(string)$node->if] = !empty((string)$node->descr) ? (string)$node->descr : $key;` ?:
https://github.com/opnsense/core/blob/7d0b4b539b70681e4126415ea6957dc47a863b95/src/opnsense/mvc/app/controllers/OPNsense/Diagnostics/Api/InterfaceController.php#L45-L54
since `legacy_config_get_interfaces` returns it in uppercase:
https://github.com/opnsense/core/blob/7d0b4b539b70681e4126415ea6957dc47a863b95/src/etc/inc/config.inc#L293
and is there any objection if I try to add the ability to select multiple interfaces for the widget?

**Comment by AdSchellevis** [comment]
@kulikov-a maybe the better question is what's the impact if we remove the upper from the legacy part?

**Comment by AdSchellevis** [comment]
@kulikov-a removed previous reaction, my mistake, the description itself shouldn't break anything in my opinion.

**Comment by kulikov-a** [comment]
@AdSchellevis thanks! widget works well with `strtoupper` in API and client-side `#filterlogentriesinterfaces` rendering (also loopback interfaces showed up). trying to convert it to multiple

**Comment by kulikov-a** [comment]
clearly a workaround, not a solution. replaced by https://github.com/opnsense/core/pull/4825

**Pull request closed without merging**
