### PR TITLE
Update authgui.inc

### PR DESCRIPTION
**Pull request by Greelan**
Adding "OPNsense" to the Title text to distinguish the page from login pages for other services (useful in browser tabs)

### CODE REVIEW

**Comment by fichtner** [comment]
This is tricky: for one now one can assert which OPNsense version this is (pre-title change and post-title change) and we really should use the "branding" name here instead of hardcoding OPNsense.

As a general rule we try to avoid hardcoding it in translations. Let's test that theory...

    # git grep 'gettext.*OPNsense'
    src/www/diag_backup.php:    'OPNsense' => gettext('OPNsense Additions'),        /* XXX need specifics */
    src/www/interfaces.php:                                <input name="adv_dhcp_pt_values" type="radio" value="OPNsense"/><?=gettext("OPNsense Default");?>
    src/www/system_authservers.php:                      <?= gettext("Limit the groups which may be used by ldap, keep empty to consider all local groups in OPNsense. ".

**Comment by Greelan** [comment]
Just a suggestion. Feel free to close.

**Comment by mimugmail** [comment]
Yep, I'll take care :)

**Comment by fichtner** [comment]
I don't want to complain or block, just dropped my review thoughts yesterday. I'll take care of this today :)

**Comment by fichtner** [comment]
Had to work around some bitrot in this area thus a bit larger in the final patch. No ETA for inclusion yet. Thanks for the suggestion!

**Comment by Greelan** [comment]
Ah, I see what you mean now by the reference to branding, looking at that commit. Point noted.

**Pull request closed without merging**
