### PR TITLE
Add modulate state as an option for state tracking

### PR DESCRIPTION
**Pull request by phpb-com**
Seems like most of the work for that was in the code already, only GUI option was missing. This commit adds the option in the GUI with appropriate checks, that are identical to synproxy state.

### CODE REVIEW

**Comment by fichtner** [comment]
I'm leaving this for @AdSchellevis -- it looks ok, but the new rules have a "modulate" state and sometimes use it. I don't know if "modulate" or "modulate state" is the expected tag here...

**Comment by phpb-com** [comment]
modulate state is the correct tag that is expected, already tested the change and done pfctl -f /tmp/rules.debug , loads without any issues.

**Comment by fichtner** [comment]
I'm not questioning that. :) I merely found other parts that were untouched and look suspiciously out of sync:

https://github.com/opnsense/core/blob/master/src/etc/inc/filter.lib.inc#L195
https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Firewall/FilterRule.php#L211-L222

**Comment by AdSchellevis** [comment]
@phpb-com thanks for your contribution, when we use the new code base for generating rules this should still work because our default parsing ignores the additional "state" https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/library/OPNsense/Firewall/FilterRule.php#L221

**Pull request merged**
