### PR TITLE
firewall, replace static logic with plugin code

### PR DESCRIPTION
**Pull request by AdSchellevis**
There's still more work to do here (for example https://github.com/opnsense/core/issues/1326), but this batch cleans up most of the filter logic underneath. 
It would probably be best to cherry-pick the changes into master, the commits are quite logically ordered.

### CODE REVIEW

**Comment by fichtner** [comment]
@AdSchellevis one more, I now get:

    06-12-17 18:44:18 [ There were error(s) loading the rules: /tmp/rules.debug:123: keep state on block rules doesnt make sense - The line in question reads [123]: block in  log quick on enc0 inet from {192.168.77.30} to {any} keep state label USER_RULE ]

Rule in question is a user rule on IPsec tab

**Comment by fichtner** [comment]
reject has the same issue

**Comment by AdSchellevis** [comment]
@fichtner will check right away

**Comment by AdSchellevis** [comment]
fixed https://github.com/opnsense/core/tree/88c5005d0cf3f567a842e136de051a995f50a428

**Comment by fichtner** [comment]
works, thanks!

**Pull request merged**
