### PR TITLE
HTML Compliance - Attribute "type" on Element <i>

### PR DESCRIPTION
**Pull request by NOYB**
Error: Attribute "type" not allowed on element "i" at this point.

### CODE REVIEW

**Comment by NOYB** [comment]
There will be two very simple to resolve merge conflicts with "HTML Compliance - Obsolete table attributes - II (few stragglers)" #2056.
You can easily fix them or wait for me to see the conflicts pop up and I'll fix them so this can be merged cleanly.

**Comment by fichtner** [comment]
OK, I'll pull #2055 in first.

**Comment by NOYB** [comment]
Rebased and pushed.  Conflicts resolved.

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
