### PR TITLE
core: update config for squid version 4

### PR DESCRIPTION
**Pull request by fabianfrz**
Don't merge as long as we are using v3

### CODE REVIEW

**Comment by fabianfrz** [comment]
@fichtner don't forget about this.

**Comment by fichtner** [comment]
Sure, blocked until 19.1.1 where we can safely use both squid packages so devel can move to version 4.

**Comment by fabianfrz** [comment]
@fichtner ok, I thought this is for 19.1.0, then it's ok.

**Comment by fichtner** [comment]
merged, thanks!

**Pull request merged**
