### PR TITLE
sidebar optimisation and improvements

### PR DESCRIPTION
**Pull request by opnsenseuser**
1. sidebar optimisation and improvements
2, change variable name for better readability

### CODE REVIEW

**Comment by fichtner** [comment]
@opnsenseuser you can always force-push your old branch to update the PR so no need to close and reopen really. whatever works for you though :)

I won't be able to test this in the next two weeks due to vacation time. Just to let you know. Take your time.


Cheers,
Franco

**Comment by opnsenseuser** [comment]
@fichtner yes, I already knew that I didn't have to delete it in order to push something else. but somehow I managed to delete it instead of adding it. sometimes I have to laugh at myself. regards and thanks, René

**Comment by opnsenseuser** [comment]
@fichtner It's kind of a love-hate relationship between Github and myself

**Comment by opnsenseuser** [comment]
https://github.com/opnsense/core/assets/34602360/ace3fae3-16d4-445e-8872-afa401cb9366

**Comment by opnsenseuser** [comment]
https://github.com/opnsense/core/assets/34602360/f96146aa-9724-498c-89cb-b0a3efe2e20b

**Pull request closed without merging**
